### ISSUE TITLE
Realne zarobki serwera

### ISSUE THREAD

**Issue by AdrianJagodznski** [gammerce/sklep-sms#103]
Hej,
obecnie zarobki serwera zliczane są w następujący sposób https://prnt.sc/qne4fq
Jednak różne platformy przyjmujące płatność mają różne stawki prowizji, np.
```
pukawka sms 3.69 - zarabiamy 1.96
cssetti sms 3.69 - zarabiamy 1.50
1s1k.pl sms 3.69 - zarabiamy 1.95
```

Czy można wprowadzić do sklepu opcję podawania wartości zarobku dla każdego API płatności które dodajemy?
Skoro i tak dodając nową metodę musimy wprowadzać do ss_sms_numbers kolumny number, tariff i service to można by oprzeć to o dodanie kolumny profit w której podawana będzie realna wartość doładowania w zdefiniowanym serwisie i mapować na tej podstawie prawidłowy przychód serwera?

Pozdrawiam Adrian

**Comment by budziam** [comment]
Cześć,
akurat jestem w trakcie przerabiania cennika w sklepie. Postaram się to uwzględnić w zmianach, które wprowadzam.

**Comment by budziam** [comment]
Czy mógłbyś proszę podać taką listę z odpowiednimi prowizjami dla różnych platform?

**Comment by AdrianJagodznski** [comment]
Hej, wrzucę je tutaj edytując wpis za jakiś czas :)

**Comment by xdbx1021** [comment]
MicroSMS
Numer - wartość SMS - wpłacono do portfela 
 71480 - 1zł (1.23 z VAT) - 0.48 zł
 72480 - 2zł (2.46 z VAT) - 0.96 zł
 73480 - 3zł (3.69 z VAT) - 1.44 zł
 74480 - 4zł (4.92 z VAT) - 1.92 zł
 75480 - 5zł (6.15 z VAT) - 2.40 zł
 76480 - 6zł (7.38 z VAT) - 2.88 zł
 79480 - 9zł (11.07 z VAT) - 4.32 zł
 91400 - 14zł (17.22 z VAT) - 6.72 zł
 91900 - 19zł (23.37 z VAT) - 9.12 zł
 92022 - 20zł (24.60 z VAT) - 9.60 zł
 92521 - 25zł (30.75 z VAT) - 12.00 zł
 92550 - 25zł (30.75 z VAT) - 12.00 zł

**Comment by budziam** [comment]
@AdrianJagodznski @xdbx1021 dzięki za dane. Zostaną one uwzględnione w kolejnej wersji sklepu.

**Comment by budziam** [comment]
Pojawiła się nowa wersja [3.11.0](https://github.com/gammerce/sklep-sms/releases/tag/3.11.0), która wprowadza rozróżnienie prowizji ze względu na platformę płatności.
Zaznaczam jednak, że jest to wersja pre-release, co oznacza, że możliwe jest, iż nie wszystko będzie działać w 100% prawidłowo.

**Comment by Kowalsky001** [comment]
@budziam można usunąć Zabijakę, bo serwer już tam zamówić nie można i pewnie za niedługo zostanie zamknięta. Dodatkowo można dodać: https://getpay.pl/

**Comment by budziam** [comment]
@Kowalsky001 dzięki za informację w sprawie zabijaki!

**Comment by budziam** [comment]
Funkcjonalność została dodana w wersji [3.11.0](https://github.com/gammerce/sklep-sms/releases/tag/3.11.0)

**Comment by budziam** [comment]
@Kowalsky001 wsparcie dla GetPay zostanie dodane w kolejnej wersji sklepu. Moduł został już zaimplementowany i dodany do źródła sklepu, dzięki uprzejmości @naXe90 https://github.com/gammerce/sklep-sms/commit/8cd8a3006ce9d2c0a13f486f8de27a58547565e9
