### ISSUE TITLE
Problem po zaktualizowaniu sklepu do najnowszej wersji

### ISSUE THREAD

**Issue by blady334** [gammerce/sklep-sms#104]
Witam,

Wczoraj zaktualizowałem sklep oraz plugin na serwerze (SOURCEMOD) do najnowszej wersji czyli v3.10.0. Problem polega na tym, że po dostaniu kodu zwrotnego i po wpisaniu go na sayu wywala taki komunikat. 

"[ShopSMS] Wprowadzono kod zwrotny: 4LXXXXXX
[ShopSMS] Trwa przeprowadzanie zakupu. Proszę czekać...
[ShopSMS] No response from the server."

Dodam, że kod zwrotny jest prawidłowy. Sprawdziłem go poprzez wpisanie na stronie sklepu. Usługa została dodana czy jakoś tak. Sprawdziłem logi sklepu oraz serwera, nic nie pokazuje (żadnego błędu). Proszę o jak najszybszą pomoc.

**Comment by budziam** [comment]
Cześć,
czy zaktualizowałeś plugin na serwerze do wersji 3.7.0: https://github.com/gammerce/plugin-sourcemod/releases/tag/3.7.0 ?

**Comment by blady334** [comment]
Tak. Właśnie po zaktualizowaniu pluginu jest problem z kupieniem usługi na serwerze

**Comment by budziam** [comment]
Z jakiej wersji sourcemod korzystasz?

**Comment by blady334** [comment]
SourceMod Version: 1.10.0.6460

    SourcePawn Engine: 1.10.0.6460, jit-x86 (build 1.10.0.6460)

    SourcePawn API: v1 = 5, v2 = 12

    Compiled on: Jan  7 2020 13:39:09

**Comment by budziam** [comment]
Wgraj proszę tą wersję pluginu: [shopsms.zip](https://github.com/gammerce/sklep-sms/files/4086508/shopsms.zip) - została skompilowana z włączonym trybem debug. Przy próbie zakupu w konsoli powinnna się pojawić wiadomość:
```
Invalid response: [...]
```
Skopiuj proszę tą odpowiedź i zamieść jako komentarz w tym zgłoszeniu.

**Comment by blady334** [comment]
Invalid response: Invalid payment platform [-1].
Invalid response: Invalid payment platform [-1].

**Comment by budziam** [comment]
Wygląda tak jakby migracja sklepu do wersji 3.10.0 nie przeszła prawidłowo. Obawiam się, że w bazie danych coś się namieszało.
Czy mógłbyś dać mi tymczasowo dostęp do Twojej bazy, żebym mógł spróbować naprawić ten błąd? Jeżeli nie masz nic przeciwko, to podeślij proszę dane dostępowe na maila seek@sklep-sms.pl

**Comment by budziam** [comment]
Problem rozwiązany
