### ISSUE TITLE
Błędne dodawanie usługi

### ISSUE THREAD

**Issue by AdrianJagodznski** [gammerce/sklep-sms#108]
Cześć,
nie wiem gdzie to napisać w sumie, www czy amx
Mianowicie złapałem dziś taki bug w sklepie
Gracz kupuje przez serwer usługę VIP na nick + hasło
Jego nick to: Buguśś
Usługa w sklepie - https://prnt.sc/qsdtd3

1. Usługa na nicku Boguśś nie działa na serwerze.
2. Dodaje usługę dla użytkownika Boguss i nie dodaje mi nowej usługi tylko dopisuje dni do usługi na nicku Boguśś
Screen: https://prnt.sc/qsdv5u
Tutaj widać, że usługa się dodała, ale nie na osobny nick tylko wszystkie 3 sumuje do jednej, zwiększając datę wygaśnięcia.

**Comment by budziam** [comment]
Wydaje mi się, że to jest oczekiwane działanie sklepu. Jeżeli istnieje już usługa wykupiona na takie dane, to ją przedłuż.
Problemem raczej jest, że 
> Usługa na nicku Boguśś nie działa na serwerze.
Myślę, że było to spowodowane tym, że w nicku były użyte polskie znaki `ś`

**Comment by AdrianJagodznski** [comment]
Imo wcześniej działały polskie znaki.
Nie jest to zamierzone działanie sklepu bo są to dwie różne osoby.
Nie mogę dodać drugiej osobie usługi do sklepu w tym wypadku.
1. Boguśś
2. Boguss

**Comment by budziam** [comment]
Ok, teraz rozumiem na czym polega problem. Postaram się go naprawić w ten weekend i wypuścić nową wersję.

**Comment by budziam** [comment]
Problem został rozwiązany poprzez zmianę kodowania kolumn w bazie danych https://github.com/gammerce/sklep-sms/commit/d3ff0f12e3e7213ac5b88d4e0e023d88f28ca12d
Zmiana zostanie wydana wraz z wersją 3.11.0

**Comment by AdrianJagodznski** [comment]
Super dzięki za poprawkę.
