### ISSUE TITLE
problem z pluginem

### ISSUE THREAD

**Issue by Sn1p3rs** [gammerce/sklep-sms#109]
L 01/24/2020 - 22:02:56: [AMXX] Plugin says: Error 22 - Obecna wersja pluginu nie jest juz wspierana. Dokonaj aktualizacji pluginu.

to samo jest na wersji:
3.8.2
3.8.1

**Comment by budziam** [comment]
Z jakiej wersji sklepu korzystasz?

**Comment by Sn1p3rs** [comment]
3.11.0

**Comment by budziam** [comment]
Zapoznaj się proszę z tym wątkiem: https://github.com/gammerce/plugin-amxmodx/issues/6
