### ISSUE TITLE
Brak serwera - edycja usługi

### ISSUE THREAD

**Issue by naXe90** [gammerce/sklep-sms#117]
Podczas edytowania usługi graczowi nie pokazuje serwera(ów) na liście

> <select id="server_id" name="server_id">
  {"return_id":"no_access","text":"Nie jeste\u015b zalogowany\/a lub nie masz odpowiednich uprawnie\u0144.","positive":false}
</select>

Serwery pojawiają się dopiero, gdy jesteśmy zalogowani również na stronie głównej sklepu.
Drugi problem jest taki, że nie da się edytować usługi graczowi, każda próba kończy sie komunikatem: `Nie udało się wyedytować usługi.`

Pole 'ID użytkownika' gdy jest na 0 to uniemożliwia edycje, po ustawieniu nawet na ID innego użytkownika niby usługa się edytuje, ale... nie edytuje. Dane zostają bez zmian.

**Comment by budziam** [comment]
Dzięki za dużo wartościowego feedbacku.

1. Błąd z pojawianiem się serwerów naprawiony
2. Błąd z id użytkownika 0 został już naprawiwony i zostanie to zawarte w kolejnej wersji
3. Z tego co widzę w kodzie, to pomimo tego, że formularz umożliwia zmianę usługi w usłudze gracza (np z vip na vippro), to serwer nie umie tego obsłużyć. Wygląda na to, że ten błąd istnieje już od jakiegoś czasu. Jutro postaram się to naprawić i wypuścić nową wersję wraz z poprzednimi poprawkami.

**Comment by budziam** [comment]
Wypuściłem nową wersję [3.11.4](https://github.com/gammerce/sklep-sms/releases/tag/3.11.4), która rozwiązuje wspomniane problemy. Daj proszę znać, czy wszystko działa tak jak powinno.
