### ISSUE TITLE
Dodawanie usług 

### ISSUE THREAD

**Issue by DaveZ07** [gammerce/sklep-sms#121]
W wersji 3.11.4 nie mozna dodawać nowych uslug, wyswietla się "nie wszystkie dane formularza zostały wypełnione"

**Comment by budziam** [comment]
Cześć,
mógłbyś podesłać screenshot wypełnionego formularza dodawania nowej usługi, który nie przechodzi?

**Comment by DaveZ07** [comment]
https://imgur.com/GR5vNNI

**Comment by budziam** [comment]
Poprawka tego błędu została zawarta w kolejnej wersji [3.11.0-rc.6](https://github.com/gammerce/sklep-sms/releases/tag/3.11.0-rc.6). Proszę potwierdź, czy problem został rozwiązany.
Nazewnictwo wersji uległo małej zmianie, stąd też taka nazwa kolejnej wersji.
