### ISSUE TITLE
Rozróżnianie stawek prowizji SMS

### ISSUE THREAD

**Issue by AdrianJagodznski** [gammerce/sklep-sms#127]
Witam,
gdzie znajdę teraz informacje o tym jaki jest przychód dla stawki sms danego operatora płatności?
W PA nie widzę ustawień od tego.

Czy to jest to https://prnt.sc/r0l9rw
Podane w groszach? :)

**Comment by budziam** [comment]
Cześć,
tak, to jest dokładnie to. Jeżeli masz sugestię by zmienić prowizję dla danego operatora, możesz stworzyć pull request ze zmianą, lub opisać to w zgłoszeniu (issue).
Zmiany zostaną dodane w kolejnej wersji sklepu.
