### ISSUE TITLE
[BUG] Wykres przychodu

### ISSUE THREAD

**Issue by AdrianJagodznski** [gammerce/sklep-sms#128]
Witam,
w zakładce z przychodem na górze znajduje się ładny wykresik, jak na niego najedziemy wyskakuje dymek z konkretnymi zarobkami serwera, ale często się on chowa pod zawartość.
Sprawdzałem to na monitorach 15' i 21'
https://prnt.sc/r0pd7a
Proszę o naprawę :)

**Comment by budziam** [comment]
Dzięki za zgłoszenie. Poprawka tego błędu zostanie zawarta w kolejnej wersji sklepu.

**Comment by budziam** [comment]
Poprawka została zawarta w https://github.com/gammerce/sklep-sms/releases/tag/3.12.0-rc.1 Zanim zdecydujesz się na aktualizację, pamiętaj, że ta wersja nie jest jeszcze stabilna i mogą występować drobne błędy.
