### ISSUE TITLE
Błąd liczenia przychodu

### ISSUE THREAD

**Issue by AdrianJagodznski** [gammerce/sklep-sms#135]
Gracz zakupił i opłacił usługę jak na screenie przelewem
https://prnt.sc/r3z3sx

Jednak w przychodzie nigdzie nie pojawiła się kwota za usługę.
Po nim jakiś gracz zakupił usługę przez sms i to normalnie wpadło do przychodu.

**Comment by budziam** [comment]
Z jakiego API do płatności przelewem korzystasz?

**Comment by AdrianJagodznski** [comment]
Microsms - sytuacja była jednorazowa.

**Comment by budziam** [comment]
Jeżeli płatność była wykonana w trybie testowym, wtedy nie jest wliczana do przychodu. Możesz sprawdzić w tabeli `ss_payment_transfers`, czy masz jakieś wiersze z kolumną `free` o wartości `1`.

Tak jak poniżej
![Screenshot from 2020-02-24 11-48-02](https://user-images.githubusercontent.com/10908895/75146739-fbd45c80-56fb-11ea-893f-cdd4af996438.png)

**Comment by xdbx1021** [comment]
Płatność nie była wykonana w trybie testowym. Na MicroSMS, jak i na mailu, jest kwota odpowiednia, tylko jej nie dodało do przychodów.

**Comment by budziam** [comment]
W takim razie jest to bardzo dziwna sytuacja. Może jakiś błąd po stronie microsms?

**Comment by AdrianJagodznski** [comment]
Ten błąd powtarza się ciągle, 4 razy już tak miałem, nie wlicza w ogóle przelewów do przychodu.

**Comment by budziam** [comment]
Z jakiej wersji sklepu korzystasz?

**Comment by AdrianJagodznski** [comment]
Dodamy w/w 
Co do wersji używamy v3.11.0

**Comment by budziam** [comment]
Wydaje mi się, że udało mi się naprawić ten błąd. Podmieńcie poniższy plik na serwerze, ścieżka `includes/Verification/PaymentModules/Microsms.php`.
[Microsms.php.zip](https://github.com/gammerce/sklep-sms/files/4267244/Microsms.php.zip)

Jeżeli problem przestanie występować, to poprawkę dodam do kolejnej wersji sklepu

**Comment by AdrianJagodznski** [comment]
Chyba działa, ale potestuje jeszcze.
