### ISSUE TITLE
Monety

### ISSUE THREAD

**Issue by Roughster62** [gammerce/sklep-sms#137]
Witam. Do sklepu-sms chciałbym dodać możliwość zakupu monet.

To są natywy systemu monet:
`register_native("cod_get_user_coins", "GetCoins", 1);
	register_native("cod_set_user_coins", "SetCoins", 1);`

Plugin Sklepu-Sms:
```#include <amxmodx>
#include <shop_sms>
native get_user_bm(id);
native set_user_bm(id, ilosc);

new const service_id[MAX_SERVICE_ID + 1] = "gxm_bm";
#define PLUGIN "Sklep-SMS: Usluga GXM BM"
#define AUTHOR "SeeK"

public plugin_natives() {
	set_native_filter("native_filter");
}

public plugin_init() {
	register_plugin(PLUGIN, VERSION, AUTHOR)
}

public plugin_cfg() {
	ss_register_service(service_id)
}

public ss_service_bought(id, amount) {
	set_user_bm(id, get_user_bm(id)+amount);
}

// Zabezpieczenie, jezeli plugin jest odpalony na serwerze bez odpowiednich funkcji
public native_filter(const native_name[], index, trap) {
	if(trap == 0) {
		register_plugin(PLUGIN, VERSION, AUTHOR); // Rejestrujemy plugin, aby nie bylo na liscie unknown
		pause_plugin();
		return PLUGIN_HANDLED;
	}
	
	return PLUGIN_CONTINUE;
}
```

Mój przerobiony:
```#include <amxmodx>
#include <codmod>
#include <shop_sms>

native cod_get_user_coins(id) // zwraca ilosc monet
native cod_set_user_coins(id, wartosc) // ustawia ilosc monet

new const service_id[MAX_SERVICE_ID + 1] = "monety";
#define PLUGIN "Sklep-SMS: Usluga MONETY"
#define AUTHOR "SeeK"

public plugin_natives() {
	set_native_filter("native_filter");
}

public plugin_init() {
	register_plugin(PLUGIN, VERSION, AUTHOR)
}

public plugin_cfg() {
	ss_register_service(service_id)
}

public ss_service_bought(id, amount) {
	cod_set_user_coins(id, cod_get_user_coins(id)+amount);
}

// Zabezpieczenie, jezeli plugin jest odpalony na serwerze bez odpowiednich funkcji
public native_filter(const native_name[], index, trap) {
	if(trap == 0) {
		register_plugin(PLUGIN, VERSION, AUTHOR); // Rejestrujemy plugin, aby nie bylo na liscie unknown
		pause_plugin();
		return PLUGIN_HANDLED;
	}
	
	return PLUGIN_CONTINUE;
}
```

Ale gdy na serwerze ktoś chcę kupić monety i wpisuję kod oraz klika enter wyskakuje błąd:
```
[SKLEP-SMS] Trwa przeprowadzanie zakupu...
[SKLEP-SMS] Zapytanie zwrocilo bledny http code.
```

Byłby ktoś w stanie pomóc mi to ogarnąć?

**Comment by Vakos321575** [comment]
@budziam 
Przyłączam się do sprawy - u mnie również występuje ten błąd.
Logi są puste.

`[SKLEP-SMS] Zapytanie zwrocilo bledny http code.`

`51.75.55.144 - - [23/Feb/2020:21:15:41 +0100] "POST /api/server/purchase?key=370d6ed88e2f11ad5021308ca220c3ca&language=polish HTTP/1.1" 500 451 "-" "amxmodx"`
`54.37.129.181 - - [23/Feb/2020:21:14:41 +0100] "GET /api/server/config?key=370d6ed88e2f11ad5021308ca220c3ca&ip=54.38.141.231&port=27015&version=3.9.0 HTTP/1.1" 200 2625 "-" "amxmodx"`
`51.75.55.144 - - [23/Feb/2020:21:15:41 +0100] "POST /api/server/purchase?key=370d6ed88e2f11ad5021308ca220c3ca&language=polish HTTP/1.1" 500 451 "-" "amxmodx"`

**Comment by budziam** [comment]
@Roughster62 czy dodałeś usługę w panelu sklepu w zakładce `Usługi`?

**Comment by Roughster62** [comment]
@budziam Tak, moduł: INNE id: monety

**Comment by budziam** [comment]
Wydaje mi się, że udało mi się zidentyfikować problem. Postaram się na dniach wypuścić poprawkę.

**Comment by budziam** [comment]
Poprawka została zawarta w wersji [3.12.0-rc.3](https://github.com/gammerce/sklep-sms/releases/tag/3.12.0-rc.3)

**Comment by Roughster62** [comment]
Kolejne błędy podczas dodawania usługi:
https://imgur.com/nVXrCB9.png

**Comment by budziam** [comment]
Wygląda, jakby nie wszystkie pliki Ci się skopiowały na FTP. Spróbuj skopiować je jeszcze raz.

**Comment by Roughster62** [comment]
Spróbowałem po kilku minutach i bez problemu dało się dodać.
Dzięki za szybką aktualizację.
