### ISSUE TITLE
Problem z automatem

### ISSUE THREAD

**Issue by Vakos321575** [gammerce/sklep-sms#14]
Witam.
Problem występuje przy edytowaniu usługi w zakładce " Czasowe usługi użytkowników" - po edycji np: wydłużenia czasu trwania usługi automat automatycznie usuwa ową usługę.
Jesteś w stanie to sprawdzić i poprawić? @budziam

**Comment by budziam** [comment]
Cześć,
czy problem występuję na stronie sklep.sklep-sms.pl czy w Twoim sklepie? Z jakiej wersji sklepu korzystasz?

**Comment by Vakos321575** [comment]
Problem występuje w moim sklepie. Sklep został zaktualizowany do najnowszej wersji, czyli 3.6.1

**Comment by budziam** [comment]
Uruchomiłem testowo sklep. Wykonałem te kroki o których mówisz, ale usługa nadal widnieje w panelu.
Nie jest przypadkiem tak, że ustawiasz datę na przeszłosc i dlatego usluga jest usuwana? Może jakis narzedzie od autouzupelniania formularzy cos psuje np. lastpass?

**Comment by Vakos321575** [comment]
Nie wydaje mi się. Jak znajdę dokładnie gdzie to leży to dam znać
