### ISSUE TITLE
Brak zapisu do bazy.

### ISSUE THREAD

**Issue by moszna** [gammerce/sklep-sms#142]
Problem objawia się tym, że jak sie wpisuje kod sms na serwerze jest blad krytyczny api. Drugi nie można nic edytować i usuwać przez panel. Blad pol;aczenia z baza. Pewnie to jest powiazane.
[Tue Mar 03 20:54:38.649468 2020] [allowmethods:error] [pid 10147:tid 139847024142080] [client ] AH01623: client method denied by server configuration: 'PUT' to /home/a/sklep/api, referer: https://xxxx/sklep/admin/pricing

**Comment by budziam** [comment]
Z tego logu, który podesłałeś wynika, że konfiguracja Twojego serwera nie pozwala na wykonywanie zapytań typu `PUT` - czego wymaga sklep do prawidłowego działania. Myślę, że powinieneś odezwać się do swojego hostingu, żeby to odblokowali.

**Comment by moszna** [comment]
Ok, bład z zapisem juz sie nie pojawia. Mam tylko problem z api 1s1k. Treść: SHOT Numer: 7355 Kod błędu: server_error

**Comment by budziam** [comment]
Z tego co widzę, to w przypadku wprowadzenia błędnego kodu sms wyświetla się nieprawidłowa wiadomość o błędzie. Poprawię to w kolejnej wersji sklepu.

**Comment by moszna** [comment]
Mircosms tez nie działa. Nieudana autoryzacja transakcji:  Kwota:  Usługa:

**Comment by budziam** [comment]
Błąd z 1s1k został naprawiony w wersji [3.12.0](https://github.com/gammerce/sklep-sms/releases/tag/3.12.0). Sprawdź proszę, czy problem ustał.

**Comment by budziam** [comment]
Pozwolę sobie zamknąć to zgłoszenie. Gdyby błąd nadal występował, daj znać.
