### ISSUE TITLE
Wykres przychodu

### ISSUE THREAD

**Issue by Vakos321575** [gammerce/sklep-sms#144]
Po najechaniu myszką na wykres na dany serwer czasami tabela która się pojawia zjeżdża w dół bądź w górę i nie widać reszty serwerów.
https://i.imgur.com/wEbF4Li.png

**Comment by budziam** [comment]
Z jakiej wersji sklepu korzystasz?

**Comment by Vakos321575** [comment]
Wersja - v3.11.0

**Comment by budziam** [comment]
Przede wszystkim, bardzo Ci dziekuję za zgłoszenie. Wydaje mi się, że Twój problem jest podobny do tego, niedawno zgłoszonego: https://github.com/gammerce/sklep-sms/issues/128
Poprawka zostanie wydana wraz z wersją 3.12.0
