### ISSUE TITLE
Kody SMS do wykorzystania

### ISSUE THREAD

**Issue by xdbx1021** [gammerce/sklep-sms#145]
Moja propozycja: 
Kody sms dodane poprzez panel, aby usuwały sie z automatu po 7 czy tam 14 dniach.

**Comment by budziam** [comment]
Czemu chciałbyś aby tak to działało?

**Comment by xdbx1021** [comment]
Kody trzeba samemu usuwać, bo są osoby, które jak dostaną go, to nie używają. Wtedy się one mnożą.
Dlatego najlepszym rozwiązaniem było by możliwość ustawienia po jakim czasie mają się usuwać darmowe kody lub przy dodawaniu, aby była opcja ustawienia ważności kodu.

**Comment by budziam** [comment]
Ustawienie ważności kodu brzmi jak dobry pomysł. Postaram się dodać taką funkcjonalność.

**Comment by budziam** [comment]
Dodałem tę funkcjonalność w najnowszej wersji [3.12.0](https://github.com/gammerce/sklep-sms/releases/tag/3.12.0)
