### ISSUE TITLE
System rabatowy

### ISSUE THREAD

**Issue by naXe90** [gammerce/sklep-sms#146]
Niżej opis jakby to miało wyglądać. Wartości procentowe oraz kwoty są dodane tylko do wglądu.

Za każde wydane 5 zł w sklepie, użytkownik otrzymuje 1% rabatu na kolejne zakupy. Maksymalnie można uzbierać 5% rabatu. Po przedłużeniu aktywnej usługi lub kupieniu kolejnej podczas posiadania już minimum jednej aktywnej, użytkownik otrzyma dodatkowe 5% rabatu do zakupu, co może dać łącznie 10% rabatu.

**Comment by budziam** [comment]
Cześć, pomysł ciekawy, ale też bardzo wymagający czasowo. Na razie chciałbym się skupić na dodawaniu obsługi kolejnych API płatności.
