### ISSUE TITLE
Problem- error

### ISSUE THREAD

**Issue by p4strike** [gammerce/sklep-sms#150]
Problem polega na tym, że gdy gracz kupi VIP to pod !sklepsms pokazuje do kiedy go ma itd. lecz nie posiada tego VIPA uprawnień. Logi poniżej. Prosiłbym o pomoc.

 Error: 210. An error occured while loading player's services.
Details: Illegal mix of collations (utf8mb4_polish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='
[shopsms.smx] Error: 210. An error occured while loading player's services.
Details: Illegal mix of collations (utf8mb4_polish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='
 [shopsms.smx] Error: 204. An error occured while loading players' services.
Details: Lost connection to MySQL server during query

**Comment by budziam** [comment]
Z jakiej wersji pluginu i sklepu WWW korzystasz?

**Comment by p4strike** [comment]
Wersja pluginu 3.8 a sklepu 3.11.0

**Comment by budziam** [comment]
Logi, które podałeś sugerują, że występuje problem w połączeniu z bazą danych. W najnowszej wersji sklepu [sklep 3.12.0](https://github.com/gammerce/sklep-sms/releases/tag/3.12.0), [plugin 3.9.0](https://github.com/gammerce/plugin-sourcemod/releases/tag/3.9.0) zostało usunięte nawiązywanie połączenia z bazą danych.
Dlatego też sądzę, że aktualizacja do najnowszej wersji może naprawić Twój problem. Zaktualizuj sklep i daj znać, czy problem nadal występuje.

**Comment by p4strike** [comment]
Jak na razie problem ustąpił i usługi działają jak należy. Dziękuję za pomoc :)

**Comment by budziam** [comment]
Pozwolę sobie zamknąć to zgłoszenie. Gdyby problem znowu się pojawił - daj znać.
