### ISSUE TITLE
Regex error. Pattern: ^status:(.*)$, Error: , Reg: 0

### ISSUE THREAD

**Issue by AdrianJagodznski** [gammerce/sklep-sms#152]
Gracz nie może zakupić usługi na serwerze, a w logach konsoli i sklepsms.log takie kwiatki:

`L 03/19/2020 - 13:43:40: Taksi ZRT; UKRYTEIP; STEAM_1:0:41669564. Wprowadzono kod: UKRYTY
L 03/19/2020 - 13:44:55: Taksi ZRT; UKRYTEIP; STEAM_1:0:41669564. Wprowadzono kod: UKRYTY
L 03/19/2020 - 13:57:21: Taksi ZRT; UKRYTEIP; STEAM_1:0:41669564. Wprowadzono kod: UKRYTY
L 03/19/2020 - 13:59:23: Taksi ZRT; UKRYTEIP; STEAM_1:0:41669564. Wprowadzono kod: UKRYTY
L 03/19/2020 - 13:59:25: Regex error. Pattern: ^status:(.*)$, Error: , Reg: 0`

Log ze sklepu:
`Transakcja SMS użytkownika: ()(UKRYTEIP) nie powiodła się. Użyto kodu zwrotnego: UKRYTY Treść: MSMS.PR Numer: 73480 Kod błędu: unknown_error`

W czym tkwi problem?

**Comment by budziam** [comment]
1. Z jakiej wersji sklepu korzystasz?
2. Z jakiego API płatności korzystasz?

**Comment by AdrianJagodznski** [comment]
Na serwerze: 3.9.1-rc.1
Na www:  v3.12.0 
API: microsms

Zaraz aktualizuję amxx do najnowszej - łączę się do bazy, nie przez token.

**Comment by budziam** [comment]
Daj proszę znać, czy aktualizacja do najnowszej wersji pomogła.

**Comment by AdrianJagodznski** [comment]
Sprawdzenie może zająć około tygodnia, bo taki problem występował raz na X dni. 
Będę obserwował i poinformuje jak coś się powtórzy.

**Comment by budziam** [comment]
Jeżeli problem się powtórzy przy najnowszej wersji, daj znać. Na razie zamknę to zgłoszenie.
