### ISSUE TITLE
Po aktualizacji sklepu i serwera z wersji 3.10.0 do 3.12.0

### ISSUE THREAD

**Issue by blady334** [gammerce/sklep-sms#153]
Po aktualizacji sklepu i serwera z wersji 3.10.0 do 3.12.0 nie działają usługi, wywala mi błędy w konsoli:

PutClientInServer: no info_player_start on level
L 03/20/2020 - 18:32:00: [SM] Exception reported: String formatted incorrectly - parameter 2 (total 1)
L 03/20/2020 - 18:32:00: [SM] Blaming: shopsms.smx
L 03/20/2020 - 18:32:00: [SM] Call stack trace:
L 03/20/2020 - 18:32:00: [SM]   [0] PrintToServer
L 03/20/2020 - 18:32:00: [SM]   [1] Line 126, /tmp/sources/shopsms.sp::OnClientPutInServer

PutClientInServer: no info_player_start on level
L 03/20/2020 - 18:32:32: Chat         | (STEAM_1:0:20340372) BlaDy*: !sklepsms
L 03/20/2020 - 18:32:32: [SM] Exception reported: Language phrase "License Not Validated" not found (arg 6)
L 03/20/2020 - 18:32:32: [SM] Blaming: shopsms.smx
L 03/20/2020 - 18:32:32: [SM] Call stack trace:
L 03/20/2020 - 18:32:32: [SM]   [0] VFormat
L 03/20/2020 - 18:32:32: [SM]   [1] Line 45, include/shopsms/stocks.inc::CPrintToChat
L 03/20/2020 - 18:32:32: [SM]   [2] Line 19, include/shopsms/license.inc::License_ShowShopMenu
L 03/20/2020 - 18:32:32: [SM]   [3] Line 162, /tmp/sources/shopsms.sp::ShowShopMenu
L 03/20/2020 - 18:32:32: [SM]   [4] Line 70, include/shopsms/cmd.inc::CmdShowShopMenu

Btw. w shopsms.cfg ustawiłem tak jak powinno być.

"// Server token.
// -
// Default: ""
shopsms_token "[secret]"

// Shop URL address.
// -
// Default: ""
shopsms_url "http://sklep.bladymirage.pl"

Proszę o jak najszybszą pomoc.

**Comment by blady334** [comment]
Kolejny błąd:

L 03/20/2020 - 19:13:39: [SM] Exception reported: Not enough space on the heap
L 03/20/2020 - 19:13:39: [SM] Blaming: shopsms.smx
L 03/20/2020 - 19:13:39: [SM] Call stack trace:
L 03/20/2020 - 19:13:39: [SM]   [1] Line 314, /tmp/addons/sourcemod/scripting/include/json.inc::json_decode
L 03/20/2020 - 19:13:39: [SM]   [2] Line 379, /tmp/addons/sourcemod/scripting/include/json.inc::json_decode
L 03/20/2020 - 19:13:39: [SM]   [3] Line 73, include/shopsms/server.inc::Server_LoadConfigCallback

**Comment by budziam** [comment]
Z jakiej wersji sourcemod korzystasz?

**Comment by blady334** [comment]
SourceMod Version: 1.10.0.6460
SourcePawn Engine: 1.10.0.6460, jit-x86 (build 1.10.0.6460)

**Comment by budziam** [comment]
Dodałem brakujące tłumaczenia i zwiększyłem rozmiar sterty (heap). Wgraj pliki z załączonej paczki. Daj znać czy to rozwiązało problem.
[sm.zip](https://github.com/gammerce/sklep-sms/files/4361445/sm.zip)

**Comment by blady334** [comment]
Zrobione lecz dalej nie działa tak jak powinno działać. Mimo, że załadowało usług graczy to gracze nadal nie maja vipów.

Logi:

Could not load player flags:  STEAM_1:1:xxx
Could not load player flags:  STEAM_1:1:xxxx
Could not load player flags:  STEAM_1:1:xxxx
Could not load player flags:  STEAM_1:1:xxxx
Could not load player flags:  STEAM_1:1:xxxx
Could not load player flags:  STEAM_1:1:xxxx
Could not load player flags:  STEAM_1:1:xxxx
Could not load player flags:  STEAM_1:1:xxxxx

[ShopSMS] Zaladowano 1 uslug do zakupienia.
[ShopSMS] Zaladowano 85 uslug graczy.

Drugi problem jest taki, ze po wpisaniu !sklepsms dzieje się cos takiego (screen) -> https://steamuserimages-a.akamaihd.net/ugc/771744917717756766/E939110D0046A4119CC168B9ACC90629F03E5282/ 

oraz wywala taki błąd -> 

L 03/20/2020 - 20:17:06: Chat         | (STEAM_1:0:20340372) BlaDy*: !sklepsms
L 03/20/2020 - 20:17:08: [SM] Exception reported: Language phrase "Chose Service Price" not found (arg 7)
L 03/20/2020 - 20:17:08: [SM] Blaming: shopsms.smx
L 03/20/2020 - 20:17:08: [SM] Call stack trace:
L 03/20/2020 - 20:17:08: [SM]   [0] Menu.SetTitle
L 03/20/2020 - 20:17:08: [SM]   [1] Line 370, /tmp/sources/shopsms.sp::ShowPurchasePricesMenu
L 03/20/2020 - 20:17:08: [SM]   [2] Line 345, /tmp/sources/shopsms.sp::ShopServiceActionMenu_handler

**Comment by budziam** [comment]
Przenieśmy chwilowo rozmowę na maila.
