### ISSUE TITLE
Token Serwera

### ISSUE THREAD

**Issue by AdrianJagodznski** [gammerce/sklep-sms#154]
Hej,
może by dodać gdzieś informacje w Panelu Admina zakładka Serwery jaki jest aktualnie wygenerowany token dla danego serwera?
Teraz można jedynie wygenerować nowy, a starego trzeba szukać w bazie.

**Comment by budziam** [comment]
Postaram się to dodać w kolejnej wersji.

**Comment by budziam** [comment]
Funkcjonalność została dodana w wersji [3.12.1](https://github.com/gammerce/sklep-sms/releases/tag/3.12.1) Wchodząc w edycje serwera, pojawia się pole z aktualnym tokenem. Daj proszę znać, czy to rozwiązuje Twój problem.

**Comment by AdrianJagodznski** [comment]
Gitarka!
Zamykam.
