### ISSUE TITLE
Nie można  kupić usługi

### ISSUE THREAD

**Issue by p4strike** [gammerce/sklep-sms#155]
Witam,

mam problem na serwerach taki, a mianowicie wchodząc w !sklepsms na serwerze pojawia się menu wybieram usługe np. GO VIP po czym wybieram by zakupić VIP a tutaj znika menu i nic dalej. Nie pojawia opcja wyboru płatnośći czy SMS itd. nic kompletnie.
Wersja sklepu najnowsza jak i SM również token wpisany poprawnie.

ERRORY:

 Blaming: shopsms.smx
L 03/20/2020 - 22:54:27: [SM] Call stack trace:
L 03/20/2020 - 22:54:27: [SM]   [0] Menu.SetTitle
L 03/20/2020 - 22:54:27: [SM]   [1] Line 366, /tmp/sources/shopsms.sp::ShowPurchasePricesMenu
L 03/20/2020 - 22:54:27: [SM]   [2] Line 341, /tmp/sources/shopsms.sp::ShopServiceActionMenu_handler
L 03/20/2020 - 22:54:40: [SM] Exception reported: Language phrase "Chose Service Price" not found (arg 7)
L 03/20/2020 - 22:54:40: [SM] Blaming: shopsms.smx
L 03/20/2020 - 22:54:40: [SM] Call stack trace:
L 03/20/2020 - 22:54:40: [SM]   [0] Menu.SetTitle
L 03/20/2020 - 22:54:40: [SM]   [1] Line 366, /tmp/sources/shopsms.sp::ShowPurchasePricesMenu
L 03/20/2020 - 22:54:40: [SM]   [2] Line 341, /tmp/sources/shopsms.sp::ShopServiceActionMenu_handler

**Comment by budziam** [comment]
Cześć,
pojawił się błąd przy wydawaniu wersji 3.9.0 i do paczek nie został dodany katalog z tłumaczeniami. Proszę, pobierz wersję [3.9.0](https://github.com/gammerce/plugin-sourcemod/releases/tag/3.9.0) raz jeszcze i wgraj ją na serwer. Problem powinien zostać rozwiązany.

**Comment by budziam** [comment]
Czy problem został rozwiązany?

**Comment by p4strike** [comment]
Po dłuższym testowaniu można powiedzieć, że problem rozwiązany. Wszystko działa jak należy. Dzięki za pomoc.
