### ISSUE TITLE
Nowa opcja

### ISSUE THREAD

**Issue by p4strike** [gammerce/sklep-sms#157]
Witam,

proponuje dodać nową opcję do sklepu, a mianowicie jak teraz jest możliwość przy każdym serwerze wybrania dowolnego operatora płatności SMS to można by dodać przelewy. W sensie np. na serwerze A ustawiam sobie SMS cssetti, a przelewy Cashbill. Na serwerze B SMS będą szły na hostplay, a przelewy na microsms. Opcja bardzo przydatna bo czasem ktoś chce dojść z serwerem i jest problem bo przelewy można ustawić tylko raz domyślnie gdzie mają iść i nie można pod każdy serwer ustawić osobno.

**Comment by budziam** [comment]
Dodam to do kolejnej wersji.

**Comment by budziam** [comment]
Funkcjonalność została dodana w wersji [3.12.1](https://github.com/gammerce/sklep-sms/releases/tag/3.12.1) Daj proszę znać, czy rozwiązuje Twój problem.

**Comment by p4strike** [comment]
Tak dokładnie o to chodziło. Bardzo się przyda. Dzięki!

**Comment by budziam** [comment]
Podałeś token w pliku `sklep_sms.cfg`?

**Comment by p4strike** [comment]
Tak oczywiście.

**Comment by budziam** [comment]
Czy mógłbyś wysłać mi na maila token serwera oraz adres sklepu?
