### ISSUE TITLE
Brak sumy przychodu

### ISSUE THREAD

**Issue by AdrianJagodznski** [gammerce/sklep-sms#160]
Siemanko,

nie wiem co się odwaliło, ale coś sknociłeś w nowej wersji i nie ma podsumowania przychodu na samym dole z poszczególnego serwera.

https://prnt.sc/rlplik

Mogę prosić szybki FIX? :)

**Comment by budziam** [comment]
Szybki fix: [3.12.2](https://github.com/gammerce/sklep-sms/releases/tag/3.12.2)
