### ISSUE TITLE
Kod błędu: [no_connection]

### ISSUE THREAD

**Issue by AdrianJagodznski** [gammerce/sklep-sms#162]
Serwis: Microsms 
Błąd przy zakupie Kod błędu: [no_connection]

Od gracza:
[SKLEP-SMS] Nie można się połączyć ze skryptem weryfikacyjnym.

[SKLEP-SMS] Wystąpił nieznany błąd. Zgłoś go właścicielowi sklepu.

Błąd po stronie microsms?

**Comment by budziam** [comment]
Możliwe, że zmieniło się API. Popatrzę na ten problem jutro wieczorem i spróbuję stworzyć poprawkę.

**Comment by AdrianJagodznski** [comment]
Dodam, że wczoraj wygenerowało mi w logach ftp coś takiego
`L 03/25/2020 - 19:18:53: Invalid server config response HTTP code | 522
L 03/25/2020 - 19:18:53: Error 23 - Wystapil blad podczas ladowania konfiguracji serwera.`

**Comment by budziam** [comment]
Błąd 522 to "Connection timed out". Czyli plugin nie był w stanie połączyć się z Twoją stroną internetową sklepu.

**Comment by AdrianJagodznski** [comment]
Dziękuje za informacje, zamykam.
