### ISSUE TITLE
Zarządzanie i rabaty.

### ISSUE THREAD

**Issue by Roughster62** [gammerce/sklep-sms#164]
Witam.
Piszę temat związany z zarządzaniem i rabatami.
Mianowicie przy dodaniu grupy i włączeniu opcji np:
- PRZEGLĄDANIE SERWERÓW - będzie możliwość wybrania jaki serwer można przeglądać.
Zważywszy na to, że nie każda osoba która dołączy z serwerem ma swój sklep-sms, takie rozwiązanie byłoby przydatne.
A drugą propozycją byłoby to, że przez panel można ustawiać na danym serwerze i danej usłudze rabat
Czyli zmieniam np cenę z 7zł na 3 i wpisuję w pole rabat "30%" i wtedy na serwerze po wpisaniu /sklepsms i wybraniu usługi pokazuje się takie coś:
1. Vip za 3.00 PLN + VAT ( 3.69 PLN ) [-30%] (rabat w kolorze czerwonym jak "Sklep SMS")

**Comment by budziam** [comment]
Myślę, że można by dodać takie pole rabat. Natomiast nie rozumiem o co chodzi z przeglądaniem serwerów.

**Comment by Roughster62** [comment]
Chodzi o to, że jak dołączy nowy serwer na sieć to tworzę grupę, zaznaczam w niej "Przeglądanie serwerów" na "Tak" i mogę wybrać jakie serwery może ta grupa przeglądać.
Dotyczy się to również innych opcji takich jak logi itp.
Są powiedzmy 4 serwery i 3 właścicieli.
Więc chciałbym dla pierwszej grupy dodać serwer 1 i 2, dla drugiej 3, a dla czwartej 4.
Czyli właściciel nr1 po zalogowaniu się ma dostęp tylko do swoich serwerów itd.
Podsumowując, dana grupa może przeglądać i zarządzać danymi serwerami, które wybiorę przy tworzeniu owej grupy.

**Comment by budziam** [comment]
Możliwość ustawiania rabatów została dodana w wersji [3.13.0-rc.1](https://github.com/gammerce/sklep-sms/releases/tag/3.13.0-rc.1)

Bardziej zaawansowanych opcji zarządzania serwerami nie planuję dodawać. Przy potrzebie aż tak silnego oddzielenia serwerów od siebie, rozwiązaniem będzie postawienie osobnego sklepu.

**Comment by naXe90** [comment]
A nie lepiej zrobić tak, że od razu zmniejsza cenę o wartość rabatu dla przelew/portfel?

**Comment by budziam** [comment]
Cenę można ręcznie dostosować. Rabat jest tylko wyświetlaną informacją, nie wpływa w żaden sposób na cenę. Można tam wprowadzić dowolną wartość.
