### ISSUE TITLE
Błąd z cennikiem

### ISSUE THREAD

**Issue by Roughster62** [gammerce/sklep-sms#165]
Witam.
Problem polega na tym, gdy jestem w zakładce Cennik i edytuję usługę z pierwszej strony i chcę przejść na drugą stronę to przekierowuje mnie na domena.pl/api/admin i wtedy pokazuje się biała strona z jakimś tekstem/kodem.
Oczywiście używam najnowszej wersji sklepu.

**Comment by budziam** [comment]
Cześć,
dziękuję Ci za zgłoszenie tego błędu. Pracuję nad jego rozwiązaniem.

**Comment by budziam** [comment]
Błąd został naprawiony. Poprawka będzie zawarta w kolejnej wersji sklepu.

**Comment by Roughster62** [comment]
Dzięki, zamykam.
