### ISSUE TITLE
Niedziałające przelewy.

### ISSUE THREAD

**Issue by moszna** [gammerce/sklep-sms#170]
Nie mogę dalej ogarnąć platnosci internetowych. Przelew przechodzi ale nie zapisuje do bazy.
Błąd: Nieudana autoryzacja transakcji: [269130874] Kwota: [9] Usługa: []
Wersja www aktualna.

**Comment by budziam** [comment]
Z jakiego API płatności korzystasz?

**Comment by moszna** [comment]
Microsms

**Comment by budziam** [comment]
Czy możesz odezwać się do mnie przez maila seek@sklep-sms.pl?

**Comment by budziam** [comment]
Czy problem został rozwiązany?
