### ISSUE TITLE
Rezerwacja Slota

### ISSUE THREAD

**Issue by Vakos321575** [gammerce/sklep-sms#171]
Cześć.
Chciałbym zgłosić problem z usługą "Rezerwacja Slota".
Serwer miał 31/32 a osoba z rezerwacją slota dostała komunikat, że musi wykupić rezerwację slota.
Rezerwacja slota ma flagę `b`
Gdy serwer nie jest full to gracz wchodzi i po sprawdzeniu owa osoba posiada te flagi.

Było to testowane wielokrotnie na nick czy też SID ale za każdym razem na serwer nie można wejść.
Z users.ini normalnie czyta rezerwację slota i można wejść bez problemu.

w amxx.cfg cvar ustawiony jest na 1:
`amx_reservation 1`

Czy mógłbyś sprawdzić ten problem?

**Comment by AdrianJagodznski** [comment]
Potwierdzam problem.
Flaga "b" nadana w users.ini pozwala wejść na serwer.
Usługa "Rezerwacja Slota" w sklepie sms dodająca flagi bz cały czas krzyczy o kupno slota.
Testowane na 31/32

**Comment by budziam** [comment]
Cześć,
postaram się w weekend przyjrzeć temu problemowi. Z jakiej wersji sklepu oraz AMXX korzystasz?

**Comment by AdrianJagodznski** [comment]
Wszystko najnowsze 
Wersja amx 1.9

**Comment by Roughster62** [comment]
Hmm, chyba również mam taki problem.
Wersja sklepu www jak i na serwerze najnowsza, a amxx 1.10.0.

**Comment by budziam** [comment]
@Vakos321575 albo ktoś inny, czy moglibyście podesłać swój plugins.ini? W którym miejscu macie dodany plugin sklepu?

**Comment by AdrianJagodznski** [comment]
Plugin od sklepu mam dopisany jako 1 do plugins-sklepsms.ini

**Comment by Roughster62** [comment]
@budziam Sklep mam wpisany zaraz po bansie.
amxbans_core.amxx
amxbans_main.amxx
sklep_sms.amxx

**Comment by budziam** [comment]
> Plugin od sklepu mam dopisany jako 1 do plugins-sklepsms.ini

Myślę, że to może być problematyczne. Powodem jest to, że plugin sklepu przypisuje graczom flagi w funkcji `client_authorized`. A w tej samej funkcji plugin `adminslots` (odpowiedzialny za rezerwację slotów) sprawdza czy gracz ma flagę `b`. Jeżeli plugin sklepu jest później wczytywany niż plugin `adminslots`, to powoduje, że zanim flagi zostaną przypisane graczowi, jest on już wyrzucany z serwera. Ponieważ pierwsze zostanie wykonana funkcja `client_authorized` w pluginie `adminslots`, a później dopiero w pluginie sklepu.

> @budziam Sklep mam wpisany zaraz po bansie.
> amxbans_core.amxx
> amxbans_main.amxx
> sklep_sms.amxx

A to jest dość ciekawe. Czy jest to po pluginie `adminslots`, czy przed?

**Comment by Roughster62** [comment]
Nie mam pluginu adminslots.
Tak wygląda początek plugins.ini
`; AMX Mod X plugins

; Admin Base - Always one has to be activated
amxbans_core.amxx
amxbans_main.amxx
sklep_sms.amxx`

Dodam, że używam pluginu na rezerwację slota (czyli jedno miejsce jest zawsze wolne, jak ktoś wchodzi na serwer, sprawdza czy ma flagę B i jeśli tak to wyrzuca jedną osobę, a jeśli nie to kickuje z powodem rezerwacji slota).

**Comment by AdrianJagodznski** [comment]
Dodam sklepsms przed adminslots i sprawdzę czy coś to zmieni

**Comment by budziam** [comment]
@Roughster62 jakiego pluginu używasz na rezerwację slota?

**Comment by Roughster62** [comment]
> #include <amxmodx> 
#include <amxmisc> 

// Comment if you don't want to hide true max_players  
//#define HIDE_RESERVEDSLOTS 

public plugin_init() 
{ 
	register_plugin("Slots Reservation","0.9.7","f117bomb") 
	register_cvar("amx_reservation","1") 
	
	#if defined HIDE_RESERVEDSLOTS 
	set_cvar_num( "sv_visiblemaxplayers" , get_maxplayers() - 1 ) 
	#endif 
	
} 

public client_authorized(id) {

	new maxplayers = get_maxplayers()
	new players = get_playersnum( 1 ) 
	new limit = maxplayers - 1
	new resType = get_cvar_num( "amx_reservation" ) 
	new who
	
	if ( players > limit ) //21/20
	{ 
		if ( get_user_flags(id) & ADMIN_RESERVATION ) 
		{ 
			switch(resType) {     
				case 1: 
					who = kickFresh()
				case 2: 
					who = kickLag()
			}
			if(who)  {
				new name[32]
   				get_user_name( who, name , 31 )
   				client_cmd(id,"echo ^"* %s was kicked to free this slot^"" ,name )
   			}
			return PLUGIN_CONTINUE 
		} 

		if ( is_user_bot(id) ) 
			server_cmd("kick #%d", get_user_userid(id)  ) 
		else 
			client_cmd(id,"echo ^"Server is Full.^";disconnect")
			
		return PLUGIN_HANDLED // block connect in other plugins (especially in consgreet)	 
	} 
	return PLUGIN_CONTINUE 
} 

kickLag() {
	new who = 0, ping, loss, worst = -1
	new maxplayers = get_maxplayers()
	for(new i = 1; i <= maxplayers; ++i) {
		if ( !is_user_connected(i) && !is_user_connecting(i) ) 
			continue // not used slot  
		if (get_user_flags(i)&ADMIN_RESERVATION) 
			continue // has reservation, skip him
		get_user_ping(i,ping,loss) // get ping
		if ( ping > worst ) {
			worst = ping
			who = i
		}
	}
	if(who) 
		if ( is_user_bot(who) ) 
			server_cmd("kick #%d", get_user_userid(who)  ) 
		else 
			client_cmd(who,"echo ^"Dropped due to high ping to free slot for an admin^";disconnect")
	return who  
}

kickFresh() {
	new who = 0, itime, shortest = 0x7fffffff
	new maxplayers = get_maxplayers()
	for(new i = 1; i <= maxplayers; ++i){
		if ( !is_user_connected(i) && !is_user_connecting(i) )
			continue // not used slot
		if (get_user_flags(i)&ADMIN_RESERVATION)
			continue // has reservation, skip him
		itime = get_user_time(i) // get user playing time with connection duration  
		if ( shortest > itime ) {
			shortest = itime
			who = i
		}
	}
	if(who) 
		if ( is_user_bot(who) ) 
			server_cmd("kick #%d", get_user_userid(who)  ) 
		else 
			client_cmd(who,"echo ^"Dropped due to shortest playing time to free slot for an admin^";disconnect")
	return who
}

**Comment by budziam** [comment]
Możesz podesłać swoje plugins.ini?

**Comment by AdrianJagodznski** [comment]
U nas po dodaniu sklepu przed adminslot, rezerwacja działa :)

**Comment by budziam** [comment]
@Roughster62 wypuściłem wersję [3.11.0](https://github.com/gammerce/plugin-amxmodx/releases/tag/3.11.0), która między innymi pokazuje w konsoli jakie uprawnienia otrzymuje gracz, który wchodzi na serwer. Wygląda to mniej więcej tak:
```
[shopsms.amxx] User: "chudy###<3><STEAM_0:1:21984552><172.18.0.1>" was given an access "btz"
```

Wgraj proszę tą wersję na swój serwer. Mając wykupioną rezerwację slota, spróbuj wejść na serwer gdy:
1. limit graczy nie jest osiągnięty (mniej niż 31/32)
1. limit graczy zostanie osiągniety (31/32)

Sprawdź czy w obu przypadkach w konsoli pojawiła się informacja od pluginu sklepu, że dołączyłeś na serwer i że przypisano Ci uprawnienia.
