### ISSUE TITLE
Formularz kontakt nie działa

### ISSUE THREAD

**Issue by AdrianJagodznski** [gammerce/sklep-sms#175]
Przy wysyłania wiadomości coś nie bangla 
https://prnt.sc/s36wgo
https://prnt.sc/s36wog

**Jak zreprodukować problem?**
https://sklep-sms.pl/#contact
Wywala błąd przy próbie wysłania wiadomości

**Oczekiwane zachowanie**
Wysłać zgłoszenie ofc

**Screenshots**
https://prnt.sc/s36wgo
https://prnt.sc/s36wog

**Szczegóły (proszę, wypełnij poniższe informacje)**
 - Czego dotyczy problem: Strona WWW https://sklep-sms.pl/#contact
 - Wersja strony WWW: n/n
 - Wersja pluginu: n/n

**Dodatkowy kontekst**
Chciałem się skontaktować w pewnej sprawie, jakbyś mógł podać alternatywny adres e-mail byłoby miło.

**Comment by budziam** [comment]
Dzięki za zgłoszenie! Błąd z formularzem został naprawiony. Skontaktować możesz się bezpośrednio przez maila: seek@sklep-sms.pl
