### ISSUE TITLE
Możliwość Kupna Usługi

### ISSUE THREAD

**Issue by masterofencode** [gammerce/sklep-sms#179]
** Możliwość Kupna Usługi  **
Ogólnie wpadłem na taki pomysł i jednocześnie chciałem wprowadzić do siebie mianowicie, chciałem zaproponować i z drugiej strony dostać odpowiedź. Mam usługe o nazwie x i teraz chciałbym żeby była ona kupowana tylko od strony webowej lecz nie widziana na serwerze w menu sklepu do kupienia i wiadomo żeby działała, przyda się to chociażby np opłaceniu flag czyli admina prościej mówiąc składki. Żeby działało dla amxx i sm. 
Czy istnieje taka możliwość? Plus poszukuje właśnie tego sposobu gdyż próbowałem troche pokombinować lecz i tak jest widoczne to w menu sklepu z usługami od strony serwerowej

**Comment by budziam** [comment]
Cześć,
żeby usługa była widoczna na serwerze trzeba ją aktywować na nim. Robi się to poprzez edycję serwera w ACP w zakładce serwery tak jak poniżej:

![image](https://user-images.githubusercontent.com/10908895/80081356-22bfdb00-8553-11ea-917a-14e098dfa13c.png)

Jeżeli koło usługi jest wybrana opcja "NIE", to usługi nie można kupić na danym serwerze. Co skutkuje też tym, że nie wyświetla się ona w menu sklepu na serwerze. Czy w Twoim przypadku nie wystarczy tak właśnie zrobić?

**Comment by masterofencode** [comment]
Chodzi mi wiesz o to że dodaną mam na serwer i tak dalej tylko Gdy zaznacze na "NIE"  nie będzie przypisana do serwera co za tym idzie nie będzie można jej kupić rozchodzi mi się o to że od strony serwera czyli w /sklepsms żeby nie była widoczna do zakupu, natomiast w wersji webowej tak i żeby działało jak normalna usługa bo obecnie mam mam włączoną i jest widoczna po wpisaniu /sklepsms a konsekwencją tego jest że każdy ma opcje by sobie ją kupić a chciałbym odizolować ją tak aby taki gracz nie mógł sobie ją kupić przez serwer cs lecz tylko przez strone sklepu

**Comment by budziam** [comment]
Myślę, że do tego przypadku idealnie nadadzą się grupy użytkowników. Dowolnej usłudze możesz ustawić, które grupy użytkowników mogą ją kupić. Wystarczy że ustawisz odpowiednią grupę, a następnie dodasz użytkowników, kórzy mają mieć możliwość zakupu tej usługi do tej grupy.

Usługi, które mają przypisane jakąś grupę nie wyświetlają się w liście usług do kupienia na serwerze. (w aktualnej wersji sklepu jest błąd i tak się nie dzieje, ale został on rozwiązany w tej wersji beta: [3.13.0-rc.1](https://github.com/gammerce/sklep-sms/releases/tag/3.13.0-rc.1))

**Comment by masterofencode** [comment]
A możliwość płacenia portfelem wyłączyłeś?

**Comment by masterofencode** [comment]
Plus nie wyświetla się np cena gdy już wybierzesz usługe następnie serwer i ilość dni oraz wpiszesz dane to masz tylko sms a np też dobrym rozwiązaniem było by żeby było to widoczne

**Comment by masterofencode** [comment]
Również zauważyłem błąd przy generowaniu kodu na usługi po wypełnieniu pól w miejsciu Ilośc pokazuje
`Nie wszystkie pola zostały wypełnione prawidłowo`

**Comment by budziam** [comment]
Wszystkie wspomnianie problemy powinny się rozwiązać po aktualizacji do wersji [3.13.0-rc.2](https://github.com/gammerce/sklep-sms/releases/tag/3.13.0-rc.2)

**Comment by masterofencode** [comment]
@budziam  A czy jest opcja żeby połaczyć to z paypalem? jako metode płatności. Plus znikneła opcja płatności portfelem przy etapie zakupu https://i.imgur.com/Novtabm.jpg

**Comment by budziam** [comment]
Płatności PayPal działaja poprzez serwis TPay, który jest pośrednikiem.

Zaktualizowałeś stronę do wersji rc.2?
Możesz podać adres swojej strony?

**Comment by masterofencode** [comment]
tak zaktualizowałem 
sklep.criticalfrag.pl

**Comment by budziam** [comment]
Żeby była możliwość płatności portfelem, musisz podać kwotę w polu `KOSZT PRZELEW / PORTFEL` Tak jak na screenie poniżej
![image](https://user-images.githubusercontent.com/10908895/80278839-d06cee80-86f9-11ea-8f9f-e236a3defcd6.png)

**Comment by masterofencode** [comment]
@budziam 
Mam wpisane bo gdy na serwerze wybiore opcje portfel to mi ściąga cene którą wpisałem

**Comment by budziam** [comment]
Czy mógłbyś podesłać jak masz ceny ustawione? Chciałbym odtworzyć ten problem u siebie. Albo, jeżeli nie masz nic przeciwko, możesz mi podesłać na maila dostęp do panelu sklepu, żebym mógł poklikać i zobaczyć co i jak jest ustawione.

**Comment by budziam** [comment]
Chyba już rozumiem w czym jest problem. Powinien być rozwiązany w kolejnej wersji [3.13.0](https://github.com/gammerce/sklep-sms/releases/tag/3.13.0)

**Comment by masterofencode** [comment]
@budziam 
Zaraz wrzuce :) i przy okazji zobaczymy czy usługa dodtakowe grupy mybb działa :)

**Comment by masterofencode** [comment]
@budziam 
Okej działa wszystko lecz zauważyłem jedną rzecz mianowicie przy usłudze z mybb gdy dokonaliśmy już zakupu przy ilość że na zawsze a nie ilość jaką ustaliśmy w sklepie i na jaką ona została zakupiona

**Comment by masterofencode** [comment]
Zauważyłem też coś takiego mianowicie gdy kupuje przez serwer usługe transakcja przebiegła pomyślnie pojawia sie w sklepie w czasowych usługach uzytkowników oraz we flagach że taki użytkownik zakupił itp lecz po zakupie czy też zmianie mapy nie ma flagi

**Comment by budziam** [comment]
Nie rozumiem tego co napisałeś
