### ISSUE TITLE
Brak możliwości zapłacenia przelewem

### ISSUE THREAD

**Issue by naXe90** [gammerce/sklep-sms#182]
**Opis problemu**
Nie można zapłacić za usługę przelewem, jeśli w cenniku nie ma ustawionego kosztu SMSa.

**Jak zreprodukować problem?**
Podaj kroki, które pozwolą zreprodukować problematyczne zachowanie sklepu:
1. Wejdź na stronę 'http://topfrags.pl/sklep'
2. Naciśnij na 'Super VIP' wybierz odpowiedni serwer oraz ilość 'Na zawsze' i kliknij 'Przejdź do płatności'
3. Zobaczysz błąd

**Oczekiwane zachowanie**
Powinna być opcja zakupu via przelew, a wyświetla się tylko opcja zapłacenia kodem.

**Screenshots**
http://prntscr.com/s4tp43
http://prntscr.com/s4tni9
http://prntscr.com/s4tomu

**Szczegóły (proszę, wypełnij poniższe informacje)**
 - Czego dotyczy problem: Strona WWW
 - Wersja strony WWW: 3.13.0-rc.1
 - Wersja pluginu: 3.11.0

**Comment by budziam** [comment]
Cześć,
dzięki za zgłoszenie problemu. Został on rozwiązany w wersji [3.13.0-rc.2](https://github.com/gammerce/sklep-sms/releases/tag/3.13.0-rc.2)
