### ISSUE TITLE
Najnowsza wersja sklepu oraz kontakt

### ISSUE THREAD

**Issue by Roughster62** [gammerce/sklep-sms#185]
**Opis problemu**
Pobrałem najnowszą wersje sklepu wypuszczoną kilka minut temu, ale znajduje się tam więcej plików, niż w przypadku wcześniejszych wersji, np: "tests" "docker".
Jeśli chodzi o kontakt, to znowu jest problem na stronie głównej.

**Oczekiwane zachowanie**
Pomyłka, czy tak powinno być?
Jest błąd po wysłaniu wiadomości.

**Szczegóły (proszę, wypełnij poniższe informacje)**
 - Czego dotyczy problem: Strona WWW

**Comment by Roughster62** [comment]
Widzę, że zmienił się załącznik i już jest gitara, ale problem z kontaktem nadal widnieje.

**Comment by budziam** [comment]
Błąd z formularzem kontaktu został rozwiązany. Dziękuję Ci za zgłoszenie!
