### ISSUE TITLE
Problem z zapisem ustawień sklepu.

### ISSUE THREAD

**Issue by lock292** [gammerce/sklep-sms#186]
Witam, proszę o pomoc w edycji / zapisu ustawień sklepu sms podczas zapisu zmian wyskakuje okienko tak jak na ss : https://imgur.com/a/HRdltVo pozdrawiam.

**Comment by budziam** [comment]
Cześć,
prawdopodobnie jest to spowodowane tym, że ustawiłeś nieprawidłowy adres URL w polu `Adres sklepu`
Niestety w takim przypadku trzeba go zmienić ręcznie w bazie danych w tabeli `ss_settings`

**Comment by lock292** [comment]
Cześć jeżeli chodzi o ustawienia w panelu admina to chciałem je edytować zaraz po instalacji sklepu ale nie mogę zapisać zmian po wpisaniu adresu sklepu czy tam samej nazwy sklepu
https://imgur.com/pUrNtDv

sprawdzę tą tabele i dam znać

**Comment by lock292** [comment]
dodałem nazwę sklepu i url sklepu przez baze danych : https://imgur.com/fYDTwIh  ale reszta i tak nie działa 
dla testu edytowałem usługę w panelu ale też nie zapisuje zmian : https://imgur.com/VK56PaT

**Comment by budziam** [comment]
Czy mógłbyś podesłać na mojego maila seek@sklep-sms.pl dane dostępowe do panelu admina, żebym mógł przyjrzeć się bliżej temu błędowi?

**Comment by lock292** [comment]
Wysłane na podany mail ;)

**Comment by lock292** [comment]
W panelu znalazłem coś takiego : https://imgur.com/pYOs5UI

**Comment by budziam** [comment]
Potrzbujesz włączyć metody HTTP: DELETE, PUT, PATCH itp. 
tutaj znalazłeś jakiś poradnik, który pokazuje jak to zrobić w panelu direct admin: https://www.spidersoft.com.au/2017/directadmin-enable-put-and-delete-requests/

Najłatwiej jednak będzie Ci napisać do supportu Twojego hostingu w którym masz postawioną stronę WWW

**Comment by lock292** [comment]
Sklep już działa poprawnie zmieniłem hosting ;) poprzedni robił same problemy jak z http tak i z funkcja mail() (brak maila do weryfikacji nowego konta na forum) autorowi sklepu dziękuje za pomoc.
Proszę jeszcze o informacje jak uruchomić web pod https aktualnie działa tylko pod http
Pozdrawiam.

**Comment by budziam** [comment]
Jaki błąd Ci się pojawia, gdy próbujesz korzystać z HTTPS?

**Comment by lock292** [comment]
Pod https wygląda to tak : https://imgur.com/HK04QKE
strona : https://cs-smerfy.eu/sklep

**Comment by lock292** [comment]
Edit.
W ustawieniach sklepu zmieniłem na https i strona już działa poprawnie
ale teraz pytanie czy w shopsms.cfg na serwerze zmienić na https czy zostawić http?

**Comment by budziam** [comment]
Zmień na https

**Comment by lock292** [comment]
Zrobione, dziękuje za pomoc i pozdrawiam.
