### ISSUE TITLE
Zniżki

### ISSUE THREAD

**Issue by Vakos321575** [gammerce/sklep-sms#189]
Cześć.
Proponuję dodać dodatek w postaci zniżek na usługi dla konkretnej osoby.
Aktualnie możemy ustawić zniżki na daną usługę co jest dobrym rozwiązaniem ale proponuję dodać jeszcze inną opcję:
Przy kupowaniu usługi dodać dodatkowe pole
`Kod rabatowy:`
Administratorowi dodać zakładkę z możliwością tworzenia takich kodów z opcją ustalenia ile % zniżki nadać.

**Comment by budziam** [comment]
To się nie sprawdzi w przypadku płatności SMS, ponieważ tam są możliwe tylko konkretne kwoty. Zniżka `30%` od SMSa na kwotę:`2.46` daje w wyniku `1.72`. Niestety nie da się wysłać SMSa na taką kwotę.

**Comment by Vakos321575** [comment]
Zgadza się dlatego jedynie mogę zaproponować aby takie cudo zostało dodane tylko przy płatności: online bądź przez portfel.

**Comment by budziam** [comment]
Myślę, że dobrym pomysłem byłoby połączenie tego z funkcjonalnością "Kody do wykorzystania". Jeżeli zniżka wynosiłaby 100%, to można by ją zastosować do każdego rodzaju płatności (sms, portfel, przelew, direct billing). Jeżeli natomiast wynosiłaby 1% - 99% to można ją wykorzystać tylko przy platnosci przelew, portfel, direct billing.

Dodam to do listy rzeczy do zrobienia. Może do końca maja uda się to zrobić. Teraz jeszcze kończę pracę nad przerobienie wyglądu sklepu aby dobrze wyświetlał się na urządzeniach mobilnych.

**Comment by Vakos321575** [comment]
@budziam 
Jeżeli chodzi o wygląd sklepu - zmieniłbym wygląd panelu admina (nie ukrywam, że poprzednia wersja była lepsza ale jak już zmieniłeś to trochę trzeba ją dopracować).
1. Zakładka "Główne" oraz reszta zakładek jest wybladła a znajdujące się w zakładkach podkategorie są pogrubione i bardziej widoczne - lepiej by to wyglądało jak zakładki były by bardziej widoczne.
https://i.imgur.com/6naMXjf.png
2. Dodając usługę użytkownikowi rozjeżdża nam się panel:
https://i.imgur.com/61A6Osd.png

**Comment by budziam** [comment]
Problemy 1, 2 zostały rozwiązane w wersji [3.14.0-rc.1 ](https://github.com/gammerce/sklep-sms/releases/tag/3.14.0-rc.1)

**Comment by budziam** [comment]
Funkcjonalność zniżek została dodana w wersji [3.14.0-rc.2](https://github.com/gammerce/sklep-sms/releases/tag/3.14.0-rc.2) Zwróć uwagę, wersja nie jest oznaczona jako stabilna, co oznacza, że mogę występować na niej drobne błędy.
