### ISSUE TITLE
Sklep-sms ,a sourcebans

### ISSUE THREAD

**Issue by Tydzek** [gammerce/sklep-sms#190]
Witam,
chialbym dowiedziec sie jak prawidlowo skonfigurowac sklep-sms i sourcebans aby wspolgraly. dokladnie chodzi o nadawnie adminow poprzez kupno w sklepie ,a banowanie  ludzi na serwerze. Aktualnie sytuacja jest taka,ze jesli ktos kupi admina w sklepie i zbanuje kogos na serwerze to sourcebans pokazuje bana ale nie pokazuje jaki admin go zbanowal ,natomiast pokazuje informacje CONSOLE.

Moje pytanie wiec brzmi , czy istnieje  jakas mozliwosc aby to dzialalo poprawnie.

pozdrawiam

**Comment by budziam** [comment]
Odpowiedzialnością sklepu jest przydzielanie graczom odpowiednich flag. Zachowanie które opisujesz wynika z tego jak działa sourcebans. Sklep SMS nie ma na to wpływu.

**Comment by Tydzek** [comment]
Dzięki za odpowiedź, wolałem się upewnić :)

**Comment by xdbx1021** [comment]
Aby na stronie sourcebansa pojawił Ci się admin banujacy, to musi on zostać dodany do strony bansa (login hasło i steamid)
