### ISSUE TITLE
Brak tokenu po zakupieniu sklepu 

### ISSUE THREAD

**Issue by Dirr1993** [gammerce/sklep-sms#191]
Kupiłem licencje na 365 dni dla amxx i sourcemod pisało po zakupieniu że w ciągu 15 minut otrzymam token na e-mail minęły 24 godziny i dalej nie otrzymałem tokenu 
email: solace8@wp.pl

**Comment by budziam** [comment]
Cześć,
przenieśmy dyskusję na korespondencję mailową.
