### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Dirr1993** [gammerce/sklep-sms#194]
**Opis problemu**
W nowym wydaniu 3.14.0-rc.1 jest bug gdy wybieram serwer na którym chce kupić usługę i wybiorę czas trwania usługi to wszystko jest dobrze wyświetla cenę ale gdy nie kupie tej usługi tylko wybiorę inny serwer i ilość dni trwania usługi to już nie wyświetla ceny 

**Jak zreprodukować problem?**
Podaj kroki, które pozwolą zreprodukować problematyczne zachowanie sklepu:
1. Wejdź na stronę '...'
2. Naciśnij na '....'
3. Zobaczysz błąd

**Oczekiwane zachowanie**
Powinien pokazywać cenę za każdym razem gdy się wybierze jeden serwer a za chwile zmieni w polu wyboru serwera na inny serwer

**Screenshots**
W razie potrzeby dodaj zrzuty ekranu, aby pomóc lepiej zrozumieć problem.
tutaj nie wyświetla ceny
![d1218493849404ead12d7e2a5ec091e6](https://user-images.githubusercontent.com/60697883/81457520-b53cbd00-9196-11ea-86eb-830a5697f308.png)

tutaj wyświetla cenę
![ab2f88d7cf49b353d987eb8c0704b37c](https://user-images.githubusercontent.com/60697883/81457548-cf769b00-9196-11ea-8f85-73b1ac258d8d.png)

**Szczegóły (proszę, wypełnij poniższe informacje)**
 - Czego dotyczy problem: [Strona WWW]
 - Wersja strony WWW: [3.14.0-rc.1]

**Comment by budziam** [comment]
Cześć,
dzięki za zgłoszenie! Postaram się to niebawem naprawić i wypuścić nową wersję z poprawką

**Comment by budziam** [comment]
Błąd został naprawiony: https://github.com/gammerce/sklep-sms/commit/cf5e23174750caa66daba2eb12a255bfd3be7f29
Zmiana zostanie dodana w kolejnej wersji sklepu, która powinna się pojawić w przeciągu kilku dni.

**Comment by budziam** [comment]
Błąd został naprawiony w wersji [3.14.0-rc.2](https://github.com/gammerce/sklep-sms/releases/tag/3.14.0-rc.2) Zwróć uwagę, wersja nie jest oznaczona jako stabilna, co oznacza, że mogę występować na niej drobne błędy.
