### ISSUE TITLE
Błąd w sekcji "Akcje"

### ISSUE THREAD

**Issue by Vakos321575** [gammerce/sklep-sms#196]
**Opis problemu**
Cześć. Gdy chcemy edytować usługę w sekcji "akcje" to nie wyświetla nam się ta rubryka z opcją edytuj/usuń itd

**Jak zreprodukować problem?**
Panel admina. Wszelkie zakładki, gdzie znajduje się rubryka "akcje" -> nie otwiera nam się tabelka z tymi akcjami.
Przykład: czasowe usługi użytkowników.

**Screenshots**
https://i.imgur.com/ZouGWPP.png

**Szczegóły (proszę, wypełnij poniższe informacje)**
 - Czego dotyczy problem: Strona WWW
 - Wersja strony WWW: v3.14.0

**Comment by budziam** [comment]
Cześć,
dzięki za zgłoszenie błędu. Został naprawiony w wersji [3.14.1](https://github.com/gammerce/sklep-sms/releases/tag/3.14.1)

**Comment by Vakos321575** [comment]
Z tego co widzę teraz działa poprawnie. Dziękuję za szybką reakcje :)
