### ISSUE TITLE
Błędny komunikat

### ISSUE THREAD

**Issue by Vakos321575** [gammerce/sklep-sms#197]
**Opis problemu**
Cześć. Podczas dodawania/usuwania/edycji usługi pokazuje nam się taki komunikat: "Brak takiej podstrony".
Oczywiście usługa się dodaje itd ale takiego komunikatu raczej nie powinno być.

**Screenshots**
https://i.imgur.com/3qWuDCX.png

**Szczegóły (proszę, wypełnij poniższe informacje)**
 - Czego dotyczy problem: Strona WWW
 - Wersja strony WWW: v3.14.1

**Comment by budziam** [comment]
Cześć,
testowałem to na stronie: https://demo.sklep-sms.pl/admin/services i taki problem nie występuje. Spróbuj może usunąć ciasteczka, cache? Albo wejdź w trybie incognito i sprawdź czy problem również występuje

**Comment by budziam** [comment]
Problem został naprawiony w wersji [3.14.2](https://github.com/gammerce/sklep-sms/releases/tag/3.14.2)
