### ISSUE TITLE
Problem UPDATE sklepu

### ISSUE THREAD

**Issue by p4strike** [gammerce/sklep-sms#198]
**Opis problemu**
Aktualizowałem sklep z wersji 3.13 do 3.14.1 i wystąpił błąd: Wystąpił błąd podczas aktualizacji. 
Poinformuj o swoim problemie. Nie zapomnij dołączyć pliku data/logs/errors.log

Po naciśnięciu właśnie aktualizuj sklep wystąpiła ta informacja i sklep nie działa.

**Szczegóły (proszę, wypełnij poniższe informacje)**
 - Czego dotyczy problem: Strona WWW, 

Wycinek z pliku errors:

http://wklejto.pl/837993

**Comment by budziam** [comment]
Problem rozwiązany
