### ISSUE TITLE
Moduł "Grupy MyBB"

### ISSUE THREAD

**Issue by karix094** [gammerce/sklep-sms#199]
Błąd podczas kupowania rangi na forum

W panelu admina dodana usługa oraz cennik
Połączenie z bazą ustawione
Podczas kupna rangi MyBB ukazuje się błąd 
"Wystąpił błąd podczas pozyskiwania danych"

**Oczekiwane zachowanie**
Sklep powinien połączyć się z bazą danych forum i przypisać użytkownika do danej grupy

**Screenshots**
https://imgur.com/a/Y2Pxdci

 - Czego dotyczy problem: [Kupno rang MyBB]
cs-fragownia.pl/shop/

**Comment by budziam** [comment]
Czy jesteś pewien, że serwer na którym jest uruchomiony sklep WWW może łączyć się z bazą forum? Często trzeba dodać adres IP do whitelisty.
