### ISSUE TITLE
Wysyłka maili

### ISSUE THREAD

**Issue by xdbx1021** [gammerce/sklep-sms#205]
Dobrze by było, abyś dodał opcję wysyłki maili  ze sklepu poprzez SMTP.

**Comment by budziam** [comment]
Dodam to do listy rzeczy do zrobienia.

**Comment by budziam** [comment]
Ta funkcjonalność pojawi się w kolejnej wersji sklepu: 3.15.0

**Comment by budziam** [comment]
Wsparcie dla SMTP zostało dodane w wersji [3.15.0](https://github.com/gammerce/sklep-sms/releases/tag/3.15.0)
Poradnik: https://github.com/gammerce/sklep-sms/wiki/Wysy%C5%82ka-maili-przy-u%C5%BCyciu-SMTP
