### ISSUE TITLE
Problem z zakładką Flagi graczy w panelu admina

### ISSUE THREAD

**Issue by Dirr1993** [gammerce/sklep-sms#207]
**Opis problemu**
Nie wiem czy tylko u mnie tak jest ale jak wchodzę w panelu w zakładkę "Flagi graczy"
to mam takie coś 

Fatal error: Uncaught Error: Call to a member function getId() on null in /home/brayan/domains/fragarena.pl/public_html/sklep/includes/View/Pages/Admin/PageAdminPlayersFlags.php:80 Stack trace: #0 [internal function]: App\View\Pages\Admin\PageAdminPlayersFlags->App\View\Pages\Admin\{closure}(Object(App\ServiceModules\ExtraFlags\PlayerFlag), 12) #1 /home/brayan/domains/fragarena.pl/public_html/sklep/includes/Support/Collection.php(30): call_user_func(Object(Closure), Object(App\ServiceModules\ExtraFlags\PlayerFlag), 12) #2 /home/brayan/domains/fragarena.pl/public_html/sklep/includes/View/Pages/Admin/PageAdminPlayersFlags.php(89): App\Support\Collection->map(Object(Closure)) #3 /home/brayan/domains/fragarena.pl/public_html/sklep/includes/View/Blocks/BlockAdminContent.php(54): App\View\Pages\Admin\PageAdminPlayersFlags->getContent(Object(Symfony\Component\HttpFoundation\Request)) #4 /home/brayan/domains/fragarena.pl/public_html/sklep/includes/View/Blocks/Block.php(26): App\View\Blocks\BlockAdminContent->content(Object(Symfon in /home/brayan/domains/fragarena.pl/public_html/sklep/includes/View/Pages/Admin/PageAdminPlayersFlags.php on line 80

**Jak zreprodukować problem?**
Podaj kroki, które pozwolą zreprodukować problematyczne zachowanie sklepu:
1. Wejdź na stronę '...'
2. Naciśnij na '....'
3. Zobaczysz błąd

**Oczekiwane zachowanie**
Jasny i zwięzły opis jak sklep powinien się w danej sytuacji zachować.

**Screenshots**
W razie potrzeby dodaj zrzuty ekranu, aby pomóc lepiej zrozumieć problem.
![49cc5accb8c5601eca2cf59eead97fb6](https://user-images.githubusercontent.com/60697883/84810558-cedde980-b00b-11ea-9566-e64fbc617306.png)

**Szczegóły (proszę, wypełnij poniższe informacje)**
 - Czego dotyczy problem: [Strona WWW]
 - Wersja strony WWW: [3.14.3]
 - Wersja pluginu: [podaj wersję]

**Dodatkowy kontekst**
Jeżeli masz coś więcej do dodania, zamieść to tutaj.

**Comment by budziam** [comment]
Cześć,
wygląda na to, że jakimś cudem istnieje w Twojej bazie usługa flagi dla gracza, która nie jest przypisana do żadnego serwera.
Gdybyś mi podesłał dane do bazy na maila (seek@sklep-sms.pl) to mogę spróbować Ci to ręcznie poprawić.

**Comment by Dirr1993** [comment]
Dziękuje za odpowiedź sam sobie poradziłem.

**Comment by budziam** [comment]
Cieszę się, że mogłem pomóc :)
