### ISSUE TITLE
Doładowanie portfela - SMS

### ISSUE THREAD

**Issue by Vakos321575** [gammerce/sklep-sms#212]
Gdy chcemy doładować portfel w sklepie, wybieramy opcję SMS i nie wyświetla nam się rubryka do wpisania kodu / treść jak i numer SMS.

Screen: https://i.imgur.com/sNwqGvk.png

 - Czego dotyczy problem: Strona WWW
 - Wersja strony WWW: v3.14.3

**Comment by Dirr1993** [comment]
zauważyłem że problem występuje na stylu retro na stylu fusion nie ma z tym problemu

**Comment by budziam** [comment]
Postaram się to poprawić dla motwu `retro` w kolejnej wersji sklepu. Na chwilę obecną mogę jedynie zasugerowac przełączenie się na motyw `fusion`

**Comment by budziam** [comment]
Błąd został naprawiony w wersji [3.15.0](https://github.com/gammerce/sklep-sms/releases/tag/3.15.0)
