### ISSUE TITLE
Nowa platforma płatności - HotPay

### ISSUE THREAD

**Issue by xdbx1021** [gammerce/sklep-sms#214]
Tak jak już było to poruszone w zgłoszeniu: #87 
Przydało by się dodanie platformy płatności - HotPay
Oczywiście tam można płacić poprzez: SMS, Przelew, Direct Billing oraz PSC.

**Comment by budziam** [comment]
Współpracuję z hotpay nad dodaniem integracji z ich serwisem. Na chwilę obecną udało się dodać obsługę płatności przelewami. Planuję jeszcze dodać SMS oraz direct billing. Co do PSC to jeszcze zobaczę, czy uda się to łatwo zintegrować.

**Comment by budziam** [comment]
@xdbx1021 dodałem integrację płatności SMS z hotpay. Na testowych danych działa prawidłowo. Przydałoby mi się to teraz przetestować na prawdziwych danych. Czy byłbyś w stanie mi z tym pomóc testując napisaną przeze mnie integrację?

**Comment by xdbx1021** [comment]
Możesz wysłać integrację, to ją sprawdzimy.

**Comment by budziam** [comment]
W wersji [3.15.1](https://github.com/gammerce/sklep-sms/releases/tag/3.15.1) została dodana obsługa płatności przelewów przez HotPay. W kolejnych wersjach postaram się dodać obsługę płatności SMS.

**Comment by Vakos321575** [comment]
@budziam 
Jak wygląda sytuacja z obsługą płatności SMS?

**Comment by Vakos321575** [comment]
@budziam 
Jakiś progres w tej sprawie?

**Comment by budziam** [comment]
Integracja z HotPay cały czas jest w planach, ale nie wiem kiedy zostanie dodana. Na razie nie jestem w stanie zadeklarować żadnej daty.
