### ISSUE TITLE
Rozbudowa SMTP + errory

### ISSUE THREAD

**Issue by LukasinSM** [gammerce/sklep-sms#215]
**Opis problemu**
Ustawienia SMTP w najnowszej aktualizacji podchodzą pod lekki żart - brakuje możliwości ustawienia portu, sposobu szyfrowania przy logowaniu, nazwy użytkownika SMTP i adresu hosta (weryfikacja SSL - teraz host to chyba zgaduj zgadula lub MX, SSL nie będzie zadowolony w wielu przypadkach).
Dodatkowo pomimo wypełnienia konfiguracji dwulinijkowej przy próbie wysłania maila pojawia się "Wystąpił błąd podczas wysyłania e-maila z linkiem do zresetowania hasła".
Sklep jest uruchomiony na PHP 7.3.19. Dodatkowo w error logach po aktualizacji wypluwa:
```
PHP Fatal error:  Uncaught Error: Class 'App\\User\\Permission' not found in /home/sklepsms.pogrywamy.pl/public_html/includes/Routing/RoutesManager.php:346
PHP Fatal error:  Uncaught TypeError: Argument 6 passed to App\\Models\\Server::__construct() must be of the type array, null given, called in /home/sklepsms.pogrywamy.pl/public_html/includes/Repositories/ServerRepository.php on line 134 and defined in /home/sklepsms.pogrywamy.pl/public_html/includes/Models/Server.php:39
```

**Jak zreprodukować problem?**
1. Zrób aktualizację.
2. Sprawdź error logi by zobaczyć błędy j/w
3. Dodaj dwie linijki do confidential/.env
4. Spróbuj zresetować hasło dla istniejącego użytkownika - błąd
5. Spróbuj zresetować hasło nie podając loginu ani maila - "sukces"

**Oczekiwane zachowanie**
Wysłanie maila z wykorzystaniem pełnej konfiguracji SMTP, wykorzystany tutaj phpmailer prowadzi wręcz za rękę.
Blokada wysłania formularza resetu hasła w przypadku braku uzupełnienia obydwu pól.

**Screenshots**
Zbędne.

**Szczegóły (proszę, wypełnij poniższe informacje)**
 - Czego dotyczy problem: Strona WWW
 - Wersja strony WWW: 3.15.0

**Comment by Vakos321575** [comment]
Potwierdzam, taki problem u nas występuje.
Dodatkowo w stylu retro w zakładce services powinny znajdować się przykładowo: `vip_desc.html` `vippro_desc.html` itd...
W celu zmiany opisu usługi bądź usunięcia informacji.
Przykładowy screen: https://i.imgur.com/9SiYY7Z.png

**Comment by budziam** [comment]
@LukasinSM błąd `Uncaught Error: Class 'App\\User\\Permission'` wygląda, jakby nie wszystkie pliki zostały prawidłowo wgrane na FTP. Sugeruję upewnić się że w folderze `includes/User` istnieje plik `Permission.php`. Najlepiej usunąć cały katalog `includes` i wgrać ten z wersji `3.15.0`

Co do braku możliwości odpowiedniej konfiguracji klienta SMTP.
Dodałem możliwość ustawienia portu oraz parametru `SMTPSecure` https://github.com/gammerce/sklep-sms/pull/216/files Czy to wystarczy, czy potrzebujesz możliwości ustawienia jeszcze jakiś wartości? 
Dodałem także logowanie błędów, aby łatwiej było zidentyfikować przyczynę ewentualnych problemów.

W ramach testów klient SMTP jest używany na stronie https://sklep.sklep-sms.pl z gsuite (gmail) i funkcjonuje prawidłowo.

---

@Vakos321575 załóż osobne issue na opisane przez Ciebie problemy.

**Comment by LukasinSM** [comment]
Nie obyło się bez modyfikacji Twojego kodu by uzyskać sensowny debug. Moja propozycja to zrobić coś pokroju:

> $mail->SMTPDebug  = 4;
			$mail->Debugoutput = function($str, $level) {
				file_put_contents('/home/supersciezka/smtp.log', gmdate('Y-m-d H:i:s'). "\t$level\t$str\n", FILE_APPEND | LOCK_EX);
			};

Jeśli jest aplikacja uruchomiona w debugu - może to komuś w przyszłości pomóc (albo i nawet Tobie) poznać realną przyczynę dlaczego nie wysyła maili po SMTP. Z funkcji których mi brakuje to możliwość wyłączenia weryfikacji certyfikatu - w naszym przypadku mamy spięte serwery przez VPN i łączymy się po wewnętrznych nazwach, więc certyfikat nigdy nie będzie prawidłowy dla takich połączeń (mimo, że usługi pocztowe mają poprawnie wystawiony certyfikat na mail.domena). Ot ochrona przed wyciekiem IP i dzieci od ddosów. 

Gdybyś chciał dodać coś takiego u siebie to wystarczy dopisać:
>$mail->SMTPOptions = array(
					'ssl' => array(
					'verify_peer' => false,
					'verify_peer_name' => false,
					'allow_self_signed' => true
				)
			);  
W przypadku wykrycia ustawienia, że ktoś nie chce mieć weryfikowanego SSL na SMTP.

Podsumowując: w naszym przypadku wymuszenie na phpmailer wyłączenia weryfikacji SSL z powodu j/w sprawiło, że zaczęło wysyłać poprawnie maile nie zdradzając naszego IP w nagłówkach.

**Comment by budziam** [comment]
Przerobiłem kod tak, żeby błędy były raportowane do pliku `data/logs/errors.log`. Dodałem także możliwość wyłączenia weryfikacji certyfikatu zgodnie z tym co wysłałeś. https://github.com/gammerce/sklep-sms/pull/216
Zmiany zostaną wypuszczone wraz z kolejną wersją sklepu.

**Comment by budziam** [comment]
W wersji [3.15.1](https://github.com/gammerce/sklep-sms/releases/tag/3.15.1)  został dodany parametr `MAIL_DISABLE_CERT_VALIDATION`, który robi dokładnie to co opisałeś.
