### ISSUE TITLE
Płatność PayPal + sugestia

### ISSUE THREAD

**Issue by Vakos321575** [gammerce/sklep-sms#217]
**Opis problemu**
Przy doładowaniu portfela PayPalem od kwoty 1,01 do 1,99 wyskakuje komunikat:
`Nie wszystkie pola formularza zostały prawidłowo wypełnione.`

Dodatkowo proponuję dodać:
W stylu retro w zakładce services powinny znajdować się przykładowo: vip_desc.html vippro_desc.html itd...
W celu uniknięcia potem pytań jak usunąć bądź dodać informacje o usłudze.

**Jak zreprodukować problem?**
1. Kliknij na doładowanie portfela.
2. Wybierz płatność PayPal
3. Wpisz przykładową kwotę: np: 1,05 i zobaczysz błąd

**Screenshots**
https://i.imgur.com/Cn75yem.png

**Szczegóły**
 - Czego dotyczy problem: Strona WWW
 - Wersja strony WWW: v3.15.0

**Comment by budziam** [comment]
Problem z paypal został naprawiony: https://github.com/gammerce/sklep-sms/commit/c9289332756c3ca8ef43a32067e6f5c9f8749113 Poprawka zostanie wypuszczona wraz z kolejną wersją sklepu.

Nie rozumiem natomiast drugiej sugestii. Mogłbyś ją jakoś inaczej opisać? Może podeślij zrzuty ekranu, które pomogą zrozumieć kontekst

**Comment by Vakos321575** [comment]
vip.desc.html służy do zamieszczenia informacji co posiada usługa VIP na stronie www. Dokładnie rozchodzi się o te informacje: https://i.imgur.com/2jvFseH.png

W wersji fusion znajdują się owe pliki a w wersji retro ich nie ma. Jest to tylko propozycja aby w przyszłości uniknąć pytań w twoją stronę jak dodać informacje o VIP bądź jak je zlikwidować.

**Comment by budziam** [comment]
Styl retro zostanie niebawem usunięty. Stąd też nie chcę tam dodawać nowych rzeczy. Pewnie masz rację, że te pliki `vip_desc.html` itp powinny się znajdować w jednym i drugim motywie.

**Comment by Vakos321575** [comment]
@budziam Kiedy można się spodziewać poprawek z kolejną wersją sklepu?

**Comment by budziam** [comment]
Cześć,
chciałem jeszcze dodać wsparcie dla hotpay w ramach kolejnej wersji, ale może po prostu wypuszczę nową, jak już to będzie gotowe. Żeby nie opóźniać niepotrzebnie tych zmian, które już są. Postaram się na dniach wypuścić nową wersję.

**Comment by budziam** [comment]
Pojawiłą się nowa wersja [3.15.1](https://github.com/gammerce/sklep-sms/releases/tag/3.15.1)
