### ISSUE TITLE
Błąd z edycja licencji

### ISSUE THREAD

**Issue by xdbx1021** [gammerce/sklep-sms#218]
**Opis problemu**
Przy chęci "zapłacenia" po zapisaniu edycji licencji (wyłączenie obsługi sourcemod) żaden przycisk nie działa. 

**Jak zreprodukować problem?**
Wejdź na stronę Twojego sklepu w wersji mobilnej. 
Wybierz opcję edycji licencji. 
Odznacz sourcemod (zostaw sam amxmodx). 
Kliknij zapisz. 
Teraz żadna opcja "płatności" nie działa (koszt 0 zł). 

**Oczekiwane zachowanie**
Możliwość edycji licencji w Twoim sklepie.

**Comment by budziam** [comment]
Dzięki za zgłoszenie. Problem został naprawiony.
