### ISSUE TITLE
Błąd po wrzuceniu plików

### ISSUE THREAD

**Issue by Kuba98** [gammerce/sklep-sms#221]
**Opis problemu**

Witam, dzisiaj wrzuciłem sklep z plikami WWW na hosting, wersja 3.15.0. Po wrzuceniu plików, chcąc zainstalować sklep wyskoczył mi błąd:
Fatal error: require(): Failed opening required '/home/*****/public_html/bootstrap/../vendor/autoload.php' (include_path='.:/opt/alt/php72/usr/share/pear') in /home/p553525/public_html/bootstrap/autoload.php on line 3
Moja wersja php to 7.4, próbowałem na innych, ale niestety to samo.

**Szczegóły (proszę, wypełnij poniższe informacje)**
 - Strona WWW

**Comment by budziam** [comment]
Cześć,
skąd bierzesz pliki sklepu, które wgrywasz na hosting?

**Comment by Kuba98** [comment]
pliki biore zaraz jak nacisne na stronie glownej WWW

**Comment by budziam** [comment]
Upewnij się proszę, że skopiowałeś folder `vendor` wraz z całą zawartością

**Comment by Kuba98** [comment]
Teoretycznie powinienem, bo wrzucałem prosto z paczki. Mógłbyś mi napisać, gdzie ten folder się znajduje? Zobaczę czy wszystko jest poprawnie

**Comment by budziam** [comment]
W głównym katalogu. Powinieneś mieć foldery `builds`, `includes`, `bootstrap` i między innymi również `vendor`

**Comment by Kuba98** [comment]
W ogóle nie miałem tego folderu, dziwne. Wrzucam i zobaczę czy będzie git
