### ISSUE TITLE
Wyskakuje mi błąd po wgraniu sklepu

### ISSUE THREAD

**Issue by Glinus** [gammerce/sklep-sms#224]
Witam, problem polega na tym, że wgrałem sklep i zamiast instalacji na stronie pokazuje mi błąd 
"Fatal error: require(): Failed opening required '/home/p560028/public_html/sklep.csmaniaki.com/vendor/composer/ClassLoader.php' (include_path='.:/opt/alt/php73/usr/share/pear') in /home/p560028/public_html/sklep.csmaniaki.com/vendor/composer/autoload_real.php on line 12" 

Oczywiście wszystko zostało poprawnie wgrane sprawdzałem każdy plik czy dobrze się wgrał... 
Nie wiem jak to naprawić bo jestem w tym zielony :/ 
Strona do tego odnośnika http://sklep.csmaniaki.com 
Kierowałem się oczywiście instrukcją zawartą na waszej stronie i również paczką która też jest na waszej stronie.

**Comment by budziam** [comment]
Wygląda na to, że nie skopiował Ci się plik `/vendor/composer/ClassLoader.php`

**Comment by Glinus** [comment]
No niestety mam wgrany ten plik i wszystkie pliki sprawdzałem czy dobrze się wgrały i nadal występuje ten problem jest w stanie Pan pomóc jeśli dałbym dostęp do ftp ?

**Comment by budziam** [comment]
Tak, pewnie. Podeślij na maila dane do FTP: seek@sklep-sms.pl O licencję się nie martw, przedłużę ją adekwatnie
