### ISSUE TITLE
Dodatkowe pole tekstowe

### ISSUE THREAD

**Issue by Vakos321575** [gammerce/sklep-sms#225]
Cześć.
W zakładce "Czasowe usługi użytkowników" przy dodawaniu usługi pod e-mail proponuję dodać kolejną opcję "Opis" lub coś w tym rodzaju aby można było dodać przykładowo za co ktoś dostał usługę, etc...

**Comment by budziam** [comment]
Postaram się to dodać w wolnej chwili

**Comment by budziam** [comment]
Cześć,
funkcjonalność została zaimplementowana: https://github.com/gammerce/sklep-sms/pull/284 i zostanie wypuszczona wraz z nową wersją sklepu.
