### ISSUE TITLE
Doładowanie portfela

### ISSUE THREAD

**Issue by Vakos321575** [gammerce/sklep-sms#226]
Cześć.
Nie można doładować portfela jakiejkolwiek osobie wpisując kwotę z przecinkiem lub z kropką (4,50 / 2.45). Dostępne są jedynie wartości tj: 4 lub 5 itd
Proszę o poprawienie i przypominam o zadanym pytaniu: https://github.com/gammerce/sklep-sms/issues/214

**Comment by DaveZ07** [comment]
Jako iż @budziam nie raczył odpowiedzieć. Przedstawiam rozwiązanie problemu.

logujemy się na FTP
wchodzimy w ścieżkę: "themes/fusion/admin/action_boxes"
edytujemy plik "user_charge_wallet.html"
w 18 linijce z " type="number" " zmieniamy na " type="value" "

naprawione :)

**Comment by budziam** [comment]
Na jakiej przeglądarce występuje ten problem? Sprawdzam to na tej stronie: https://sklep.sklep-sms.pl/page/purchase?service=charge_wallet i jestem w stanie wprowadzić kwotę np. 1.23

**Comment by Vakos321575** [comment]
Na różnych przeglądarkach był problem ale @DaveZ07 pomógł także naprawione ;)
