### ISSUE TITLE
Zmiana typu usługi

### ISSUE THREAD

**Issue by Vakos321575** [gammerce/sklep-sms#227]
Cześć, nie działa możliwość zmiany typu usługi przykładowo z nick + hasło na SID.
Teoretycznie w panelu wyświetla, że usługa jest na SID ale serwer dalej otrzymuje informację, że usługa nadal jest na nick + hasło.
W bazie auth data dalej jest na nick + hasło a nie na SID.

**Szczegóły (proszę, wypełnij poniższe informacje)**
 - Czego dotyczy problem: Strona WWW
 - Wersja strony WWW: v3.15.1

**Comment by budziam** [comment]
Czy problem nadal występuje?

**Comment by Vakos321575** [comment]
Problem nadal występuje.

**Comment by budziam** [comment]
Czy zmianę robisz z poziomu panelu administratora czy poprzez stronę "Moje usługi"?

**Comment by Vakos321575** [comment]
Z panelu administratora

**Comment by budziam** [comment]
Przed chwilą sprawdzałem to na stronie demo.sklep-sms.pl i wygląda na to, że tam problem nie występuje. Potrzebowałbym, żebyś wysłał mi na maila dostęp do panelu admina Twojego sklepu oraz dane do bazy danych. Bez tego nie będę w stanie sprawdzić w czym leży problem.
