### ISSUE TITLE
Error 23  invalid http Code 

### ISSUE THREAD

**Issue by Tydzek** [gammerce/sklep-sms#228]
Witam przesył od razu ssa z serwera aby się zbytnie jie rozpisywać, po aktualizacji sklepu error log wygląda następująco.
![Screenshot_20201021_204830_com android chrome](https://user-images.githubusercontent.com/64696165/96826666-1221ec00-1434-11eb-9295-e4b0cb6fb80f.jpg)

**Comment by DaveZ07** [comment]
Ktoś tu majstrował przy weryfikacji licencji 😉

**Comment by budziam** [comment]
Czy błąd nadal występuje?

**Comment by budziam** [comment]
Jeżeli błąd pojawi się ponownie, daj proszę znać
