### ISSUE TITLE
Nie dodaje niestandardowych usług wykonywanych przez natyw

### ISSUE THREAD

**Issue by dredek** [gammerce/sklep-sms#229]
2 dni temu w sklepie przestała działać funkcja dodawania niestandardowych usług wykonywanych przez natyw czyli przykładowo exp od coda, monety do coda. Po zakupie takowej usługi wyskakuje informacja, że zakup został dokonany tj. informacja o prawidłowym kodzie ale nie dodaje kompletnie nic. Jak wspomniałem wyżej wszystko działało bez problemów, żadne zmiany nie były wprowadzane na sklepie, problem występuje na 7 serwerach więc nie jest to problem z mojej strony i przypominam, że wystąpił 2 dni temu.
Wersja amxx: 3.5.0, 3.5.1
Wersja www: 3.6.4

Jako, że pisałem już na mailu to teraz piszę tutaj i liczę na szybką odpowiedź ze względu na to że problem jest dla mnie bardzo uciążliwy a poniosłem z tego powodu już wystarczająco duże straty.

**Comment by budziam** [comment]
Czy problem nadal występuje?

**Comment by budziam** [comment]
Jeżeli problem ponownie się pojawi, daj proszę znać
