### ISSUE TITLE
Błąd 500

### ISSUE THREAD

**Issue by dinowy** [gammerce/sklep-sms#247]
Siemka -  od wczoraj od zakupu mam w sklepie ten błąd. Powtarza się na okrągło i na serwerze wyskakuje że nie ma żadnych usług a są dodane przez stronę.

L 11/20/2020 - 19:35:58: Invalid server config response HTTP code [500]
L 11/20/2020 - 19:35:58: Error 23 - The server configuration response cannot be read.

**Comment by budziam** [comment]
Cześć,
podaj proszę adres WWW sklepu

**Comment by dinowy** [comment]
https://dope-frags.eu/shop 

Wysłane z aplikacji Poczta dla Windows 10

Od: Michał Budziak
Wysłano: środa, 25 listopada 2020 20:08
Do: gammerce/sklep-sms
DW: dinowy; Author
Temat: Re: [gammerce/sklep-sms] Błąd 500 (#247)

Cześć,
podaj proszę adres WWW sklepu

**Comment by dinowy** [comment]
Witam problem rozwiązałem sam - winny był hosting home.pl - nie polecam nikomu. Mają poblokowane porty i ogolnie smiech na sali nic nie działa.

Jednak pojawil sie kolejny problem bo mam odznaki w sklepie i wszystko dziala tylko nie moge dodac 6 poziomu czyli licencji agenta 007. Robilem wszystko tak jak jest w opisie tutaj: https://github.com/gammerce/plugin-amxmodx/wiki/Dodanie-usługi-BF2:-Odznaki.

Link do sklepu: http://dope-sklep.xaa.pl/sklep/

Zawartość bf2:  https://pastebin.pl/view/716c66a8

Tu już wymiękam bo próbowałem dosłownie wszystkiego.

**Comment by budziam** [comment]
Cześć,
zamknijmy proszę to zgłoszenie i otwórz nowe z problemem dotyczacyć bf2.
