### ISSUE TITLE
Nie czyta cennika

### ISSUE THREAD

**Issue by Naro1265** [gammerce/sklep-sms#248]
Witam, wgrałem sklep w wersji 3.15.1 dodałem serwer csgo dodałem tokena z serwera do pliku cfg na serwerze dodałem  do cennika usługi mimo wybrałem metodę płatnośći 1sk1 mimo to przy próbie kupna usługi na serwerze mam komunikat nie dodano cennika mimo,że cennik jest dodany, metoda płatności również

**Comment by budziam** [comment]
Może dodałeś cenę SMS, która nie jest wspierana przez 1s1k?

**Comment by Naro1265** [comment]
Owszem nawet razem z cs-harnas sprawdzałemd dawnym supportem tego sklepu wszystko jest skonfigurowane prawidłowo a mimo to nie czyta usługi na serwerze w 1.6 czyta bez problemu natomiast csgo leży

**Comment by budziam** [comment]
Potrzebowałbym dostęp do panelu administratora Twojego sklepu, żeby móc zdebugować problem. Mógłbyś podesłać na mail?
