### ISSUE TITLE
BF2 Brak odznaki Licencja agenta w sklepie

### ISSUE THREAD

**Issue by dinowy** [gammerce/sklep-sms#249]
Witam a więc tak mam odznaki w sklepie i wszystko dziala tylko nie moge dodac 6 poziomu czyli licencji agenta 007. Robilem wszystko tak jak jest w opisie tutaj: https://github.com/gammerce/plugin-amxmodx/wiki/Dodanie-usługi-BF2:-Odznaki.

Link do sklepu: http://dope-sklep.xaa.pl/sklep/

Zawartość bf2: https://pastebin.pl/view/716c66a8

Tu już wymiękam bo próbowałem dosłownie wszystkiego.

**Comment by budziam** [comment]
Mógłbyś podesłać screenshoty z gry i na ich przykładzie wytłumaczyć co się teraz wyświetla, a co się powinno wyświetlać?

**Comment by dinowy** [comment]
Wyświetla się normalnie tak jak powinno być, tylko ze brakuje 6go poziomu odznak. Jest dodany w sklepie ale go nie wyświetla.   Po prostu można kupić odznakę do poziomu profesjonalista, a najwyższego poziomu czyli licencji agenta 007 nie wyświetla, nie ma po prostu.   Mógłbyś podesłać screenshoty z gry i na ich przykładzie wytłumaczyć co się teraz wyświetla, a co się powinno wyświetlać? —  You are receiving this because you authored the thread.  Reply to this email directly,  github.com view it on GitHub , or  github.com unsubscribe .

**Comment by budziam** [comment]
W kodzie z linku który podesłałeś: https://pastebin.pl/view/716c66a8 jest informacja, że ten bf2 posiada 8 stopni. To jest zapisane w 45 linijce
```
#define MAX_BADGES 8
```

Natomiast Ty piszesz o tym, że maksymalny poziom to poziom 6. Czy na pewno podesłałeś dobry kod źródłowy bf2?

**Comment by dinowy** [comment]
To jest ten sprzed zmiany na sugerowany przez Ciebie w FAQ sklepu na githubie. Tam napisałeś żeby pobrać bf 2.0.0 i tak zrobiłem i nadal nie działa ani na tym ani na tym sugerowanym przez Ciebie   W kodzie z linku który podesłałeś:  pastebin.pl pastebin.pl  jest informacja, że ten bf2 posiada 8 stopni. To jest zapisane w 45 linijce #define MAX_BADGES 8 Natomiast Ty piszesz o tym, że maksymalny poziom to poziom 6. Czy na pewno podesłałeś dobry kod źródłowy bf2? —  You are receiving this because you authored the thread.  Reply to this email directly,  github.com view it on GitHub , or  github.com unsubscribe .

**Comment by budziam** [comment]
Źle zrozumiałem kod. Czy mógłbyś pokazać Twój cennik dla tej usługi?

**Comment by budziam** [comment]
Czy na pewno zdefiniowałeś cenę dla poziomu 6?
