### ISSUE TITLE
Problem ze stabilnym połączeniem

### ISSUE THREAD

**Issue by blady334** [gammerce/sklep-sms#256]
Witam,

problem polega na tym, że co jakiś czas wywala połączenie ze sklepem na serwerach CSGO (nie wszystkie na raz). Do sklepu jest 5 podłączonych serwerów CSGO.

W error logach na serwerach wyświetla się coś takiego:
"L 12/15/2020 - 23:37:27: [SM] Exception reported: Error: 15. Błąd licencji.
L 12/15/2020 - 23:37:27: [SM] Blaming: shopsms.smx
L 12/15/2020 - 23:37:27: [SM] Call stack trace:
L 12/15/2020 - 23:37:27: [SM]   [0] SetFailState
L 12/15/2020 - 23:37:27: [SM]   [1] Line 47, include/shopsms/error.inc::ShopThrowError
L 12/15/2020 - 23:37:27: [SM]   [2] Line 54, include/shopsms/license.inc::License_ValidationCallback
L 12/15/2020 - 23:39:15: Error log file session closed."

"L 12/16/2020 - 12:54:04: [SM] Exception reported: Error: 15. Błąd licencji.
L 12/16/2020 - 12:54:04: [SM] Blaming: shopsms.smx
L 12/16/2020 - 12:54:04: [SM] Call stack trace:
L 12/16/2020 - 12:54:04: [SM]   [0] SetFailState
L 12/16/2020 - 12:54:04: [SM]   [1] Line 47, include/shopsms/error.inc::ShopThrowError
L 12/16/2020 - 12:54:04: [SM]   [2] Line 54, include/shopsms/license.inc::License_ValidationCallback
L 12/16/2020 - 13:41:08: Error log file session closed."

Wersja sklepu: 3.15.0

Ten problem występuję już od jakiegoś czasu tylko nie miałem kiedy to zgłosić.

Pozdrawiam

**Comment by budziam** [comment]
Cześć,
z jakiej wersji pluginu korzystasz?
