### ISSUE TITLE
Problem z doładowaniem konta

### ISSUE THREAD

**Issue by Naro1265** [gammerce/sklep-sms#273]
Witam, przy próbie doładowania konta użytkownikowi w sklepie mam taki o to błąd Zakupiono usługę [charge_wallet]. Dane: [] Ilość: [600 charge_wallet] Serwer: [] ID transakcji: [32] Kod promocyjny: [] Email: [fxxxx@wp.pl][] Brak(Fabregas21)(2)
dodatkowo przy kliknięcie doładuj portfel wywala błąd 404 404
Strona nie została znaleziona http://sklep.cybersfera.pl/page/purchase?service=charge_wallet

**Comment by budziam** [comment]
Cześć,
wygląda jakby ktoś przypadkowo usunął usługę `charge_wallet`. Sprawdź proszę czy taka usługa istnieje na stronie  http://sklep.cybersfera.pl/admin/services

**Comment by Naro1265** [comment]
Hej wysyłam ci screena z sklepu usługa o której piszesz nie została skasowana podrzucam ci też dane do logowania na moje konto Naro Mateusz1265 
            
          
     
      
       
        Dnia 6 lutego 2021 12:11 Michał Budziak &lt;notifications@github.com&gt; napisał(a):
       
    
       
         
 Cześć,  
wygląda jakby ktoś przypadkowo usunął usługę  charge_wallet . Sprawdź proszę czy taka usługa istnieje na stronie   sklep.cybersfera.pl sklep.cybersfera.pl

**Comment by AdrianJagodznski** [comment]
Skasuj kochany te dane i zmień je.

**Comment by budziam** [comment]
Cześć,
@Naro1265 wyślij proszę te dane jeszcze raz bezpośrednio na maila seek@sklep-sms.pl Nie jako odpowiedź na tą wiadomość
