### ISSUE TITLE
3.16.1 - błąd po aktualizacji

### ISSUE THREAD

**Issue by Vakos321575** [gammerce/sklep-sms#277]
Cześć.
Po aktualizacji sklepu www do wersji 3.16.1 wywala następujący błąd w sklepie.

`Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' in /home/sklepsms.pogrywamy.pl/public_html/includes/functions.php on line 622`

Wersja PHP 7.3 -> pobrany build-7.4

**Comment by budziam** [comment]
Cześć,
build 7.4 korzysta z pewnych funkcjonalności języka, które jeszcze nie były dostępne w wersji 7.3. Muszę jakoś lepiej przemyśleć te paczki. A na chwilę obecną pozostaje mi zasugerować pobranie paczki pod wersję 5.6: https://github.com/gammerce/sklep-sms/releases/download/3.16.1/build-5.6.zip

**Comment by budziam** [comment]
Ostatecznie przerobiłem proces tworzenia nowych releasów sklepu i teraz jest tworzony build dla każdej wersji PHP. Także możesz pobrać paczkę dla PHP 7.3 i wszystko powinna działać: https://github.com/gammerce/sklep-sms/releases/download/3.16.1/build-7.3.zip

**Comment by Vakos321575** [comment]
Po update na razie działa.
