### ISSUE TITLE
Brak instalatora

### ISSUE THREAD

**Issue by StrajGer** [gammerce/sklep-sms#283]
**Opis problemu**
Problem polega na tym, że po wgraniu skryptu na serwer web i wejściu w link kierujący do skryptu od sklepu nie uruchamia się instalator - on po prostu nie istnieje, skrypt próbuje niby przekierować się do jakiegoś podfolderu "setup" który po prostu nie istnieje.

**Oczekiwane zachowanie**
Uruchomienie sie instalatora przy wgraniu pierwszy raz skryptu sklepu, bo póki co jest brana kasa za coś co nie działa.

**Screenshots**
https://imgur.com/Q7FP9Vg

**Szczegóły (proszę, wypełnij poniższe informacje)**
Strona www, wersja 3.16.1

**Dodatkowy kontekst**
Prosiłbym o naprawe, ponieważ aktualnie nie da się zainstalować strony od sklepu co uniemożliwa korzystanie z usługi za którą się zapłaciło (czytaj licencje).

**Comment by StrajGer** [comment]
Wersja php 7.2

**Comment by budziam** [comment]
Cześć,
czy mógłbyś proszę wysłać mi na mail dane do FTP sklepu, to spróbuję naprawić problem: seek@sklep-sms.pl

**Comment by StrajGer** [comment]
W jaki sposób chcesz naprawić problem lokalnie? Zbytnio nie mogę ci
podesłać danych bo mam założony klucz ssh (maszyna), problem jest po
stronie skryptu a nie u mnie, wymagania spełniam bo sprawdzałem, takie coś
co wysłałem dzieje sie po wgraniu pobranej paczki z githuba.

Sob., 6 lut 2021, 12:07 użytkownik Michał Budziak <notifications@github.com>
napisał:

**Comment by StrajGer** [comment]
zresztą, jak zrobie tak: link/index.php?=setup to przełącza na coś co przypomina instalator, ale niestety nie działa : https://fraglife.pl/shop16/index.php?=setup

**Comment by StrajGer** [comment]
> Cześć,
> czy mógłbyś proszę wysłać mi na mail dane do FTP sklepu, to spróbuję naprawić problem: [seek@sklep-sms.pl](mailto:seek@sklep-sms.pl)

To dowiem się, czy to zostanie jakoś naprawione, czy mam wysyłać jakoś te dane, co jak dla mnie jest głupie, bo mógłbyś to lokalnie przetestować i naprawić.

**Comment by budziam** [comment]
Ważność licencji zostanie przedłużona ze względu na problemy z funkcjonowaniem sklepu, tym się teraz nie martwmy. Problem mógłbym przestestować u siebie lokalnie, aczkolwiek u mnie problemu nie ma. Stąd też w jakiś sposób dostęp do twojego serwera by móc sprawdzić w czym leży problem. Mogę Ci podesłać mój klucz publiczny, który tymczasowo dodasz, abym mógł się połączyć z twoim serwerem.

**Comment by budziam** [comment]
Mogę zgadywać, że apache2 zainstalowany na Twoim serwerze nie ma włączonego modułu `rewrite`. Możesz to zrobić przy użyciu poniższej komendy
```
sudo a2enmod rewrite
sudo service apache2 restart
```

Ale czy to na pewno rozwiąże twój problem? Tego nie wiem

**Comment by StrajGer** [comment]
![image](https://user-images.githubusercontent.com/17970769/107569109-358dc400-6be8-11eb-9449-4990da6d646d.png)
Po włączeniu rewrite'a bez zmian, tylko skoro ty chcesz dostęp do ftp to co chcesz stwierdzić? Forum jakoś u mnie działa i instalowane było też, mało tego, twój stary skrypt sklepu jeszcze z folderem instalacyjnym /install/ też się normalnie zainstalował (nie pierwszy raz korzystam z usług twojego oprogramowania), natomiast z nowymi wersjami już od pewnego czasu mam problem ale wtedy zgłaszałem to o ile dobrze pamiętam jeszcze przez formularz kontaktowy, może htacces jest jakoś źle napisany? Cała paczka to 3.16.1 pobrana z githuba pod wersje 7.2, więc nic innego na ftp nie zobaczysz jak własnie te wersje sklepu ze wszystkimi jej plikami.

**Comment by budziam** [comment]
Wgrałem testowo świeżą wersję sklepu na serwer z zainstalowanych apache2 i PHP 7.2 Instalator wyświetlił się prawidłowo
![image](https://user-images.githubusercontent.com/10908895/107858724-066c9200-6e36-11eb-8c4d-9952d4ee489e.png)
Stąd też wnioskuję, że istnieje jakiś problem z konfiguracją na Twoim serwerze. Nie jest w stanie określić co to za problem bez dostępu do SSH lub FTP i możliwości zdebugowania problemu.

**Comment by StrajGer** [comment]
> Wgrałem testowo świeżą wersję sklepu na serwer z zainstalowanych apache2 i PHP 7.2 Instalator wyświetlił się prawidłowo
> ![image](https://user-images.githubusercontent.com/10908895/107858724-066c9200-6e36-11eb-8c4d-9952d4ee489e.png)
> Stąd też wnioskuję, że istnieje jakiś problem z konfiguracją na Twoim serwerze. Nie jest w stanie określić co to za problem bez dostępu do SSH lub FTP i możliwości zdebugowania problemu.

No ok, ale ty to wgeywasz / wymuszasz jako główny katalog, a spróbuj zainstalować kiedy skrypt jest w podfolderze ;) Mój serwer jest sprawny i tyle wiem, wymagania spełniam bo sprawdzałem 10 razy.

**Comment by budziam** [comment]
Sytuacja, gdy skrypt jest w podfolderze
![image](https://user-images.githubusercontent.com/10908895/108197263-6dca6080-711a-11eb-9627-92e95a8de2aa.png)

**Comment by StrajGer** [comment]
No to w takim razie sprawdze jeszcze u siebie wszystko, ale rzecz jest dziwna, bo i firum normalnie u siebie instalowałem i inne sklepy i problemu nie było nigdy takiego.

**Comment by budziam** [comment]
Tak jak pisałem wcześniej, mogę spróbować pomóc znaleźć przyczynę błędu. Aczkolwiek potrzebuję do tego przynajmniej dostępu do FTP

**Comment by StrajGer** [comment]
> Tak jak pisałem wcześniej, mogę spróbować pomóc znaleźć przyczynę błędu. Aczkolwiek potrzebuję do tego przynajmniej dostępu do FTP

A mógłbyś mi napisać z jakich modułów do apache korzystasz oprócz rewrite?

**Comment by StrajGer** [comment]
Dobra, ogarnąłem, wystarczyło w configu od apache2 zmienić AllowOverride na All i działa, szkoda tylko, że nigdzie w opisie instalacji nie jest napisane, że moduł rewrite jest kluczowy do prawidłowego funkcjonowania sklepu, jak będziesz miał chwile czasu to proponuje zroibć pełen opis potrzebnych "rzeczy" do instalacji twojego skryptu, bo domyślnie apache2 nie ma załączonego rewrite'a i ktoś może się przejechać tak jak ja.

**Comment by StrajGer** [comment]
Tak samo nie ma informacji w którym pliku można edytować liste bonusów na serwerze, praktycznie wszystkiego trzeba domyślać się samemu, zbytnio to profesjonalne nie jest.

**Comment by budziam** [comment]
Cieszę się, że problem został naprawiony. Postaram się dodać odpowiednie informacje, by na przyszłość instalacja sklepu była prostsza.
