### ISSUE TITLE
Variable must be instance of literal string

### ISSUE THREAD

**Issue by 1shotkill** [gammerce/sklep-sms#285]
Cześć,

Po update wyswietla błąd `Variable must be instance of literal string` w pliku `includes/services/UserServiceService.php` .
Chodzi o funkcje  findOne. Proszę oraz sugeruje w ramach mozliwosci zebys przywrocil do poprzedniej wersji tak jak w tym giscie https://gist.github.com/1shotkill/102ea559aa1c1d6076c9d85693181a69

```
public function findOne($userServiceId): ?UserService
    {
        $userServices = $this->find("WHERE `id` = " . intval($userServiceId));
        return $userServices ? $userServices[0] : null;
    }
```

**Comment by budziam** [comment]
Cześć,
nie mogę przywrócić tego do poprzedniej wersji, ponieważ poprzednie podejście umożliwiało atak SQL Injection. Czy mógłbyś podesłać pełen stack trace?

**Comment by budziam** [comment]
Sprawdź proszę, czy z aktualną wersją pliku działa prawidłowo: https://github.com/gammerce/sklep-sms/blob/master/includes/Service/UserServiceService.php
