### ISSUE TITLE
Błąd przy instalacji.

### ISSUE THREAD

**Issue by nNcEhR** [gammerce/sklep-sms#29]
Wystąpił błąd podczas aktualizacji. Poinformuj o swoim problemie na forum sklepu. Do wątku załącz plik errors/install.log

edit:

[install.log](https://github.com/gammerce/sklep-sms/files/2716716/install.log)

**Comment by budziam** [comment]
Cześć,
mógłbyś podesłać zawartość pliku install.log ?

**Comment by nNcEhR** [comment]
[install.log](https://github.com/gammerce/sklep-sms/files/2716723/install.log)

**Comment by budziam** [comment]
Ta poprawka powinna pomóc: https://github.com/gammerce/sklep-sms/pull/28
Wypuszczę nową wersję 3.6.5. Za kilka minut powinna się pojawić.

**Comment by nNcEhR** [comment]
Dziękuje za informacje, w takim razie czekam na nową wersję.
Pozdrawiam

**Comment by budziam** [comment]
Opublikowałem nową wersję ( na razie jako pre-release ): https://github.com/gammerce/sklep-sms/releases/tag/3.6.5

Powiedz proszę czy rozwiązała ona problem.

**Comment by nNcEhR** [comment]
Przy instalacji pojawia się ten sam komunikat. 

[install.log](https://github.com/gammerce/sklep-sms/files/2716740/install.log)

**Comment by budziam** [comment]
Mhm, no to podejście numer 2. Ponownie opublikowałem wersję 3.6.5 z kolejną poprawką. Spróbuj proszę jeszcze raz: https://github.com/gammerce/sklep-sms/releases/tag/3.6.5

**Comment by Ne3kk** [comment]
Podpinam się ten sam problem pisałem ci na poczcie(odpisz jak możesz) Dziękuje 
Taka wersja php jest kolega wyżej ma pewnie podobną
 4.5.4.1

**Comment by nNcEhR** [comment]
Wszystko działa :) W panelu.. wyskakuje co prawda komunikat "Dostępna jest aktualizacja skryptu do wersji 3.6.4. Aby ją pobrać przejdź do strony Aktualizacja strony WWW."  ale to najmniejszy problem ;)

Najnowsza wersja 3.6.4
Obecna wersja |   | 3.6.5
-- | -- | --

Mistrz... jeszcze raz dziękuje za te dwa dni walki... ;) Pozdrawiam

**Comment by budziam** [comment]
Jak oznaczę wersję jako release zamiast pre-release w panelu zniknie powyższy komunikat.

**Comment by budziam** [comment]
@Ne3kk powiedz czy wersja 3.6.5 rozwiązuje Twój problem

**Comment by Ne3kk** [comment]
Własnie sprawdzam,ale nie chce mi nawet instalka wyskoczyć&nbsp;Od: "Michał Budziak" &lt;notifications@github.com&gt;Do: "gammerce/sklep-sms" &lt;sklep-sms@noreply.github.com&gt;; Wysłane: 23:18 Sobota 2018-12-29Temat: Re: [gammerce/sklep-sms] Błąd przy instalacji. (#29)@Ne3kk powiedz czy wersja 3.6.5 rozwiązuje Twój problem

**Comment by Ne3kk** [comment]
Owszem instalacja poszła, chce się zalogować do sklep error...

**Comment by Ne3kk** [comment]
Instalka poszła,ale jest error taki? Od: "meo" &lt;aaaa19988@interia.eu&gt;Do: "gammerce/sklep-sms" &lt;reply@reply.github.com&gt;; "gammerce/sklep-sms" ; Wysłane: 23:18 Sobota 2018-12-29Temat: Re: [gammerce/sklep-sms] Błąd przy instalacji. (#29)Własnie sprawdzam,ale nie chce mi nawet instalka wyskoczyć Od: "Michał Budziak" &lt;notifications@github.com&gt;Do: "gammerce/sklep-sms" &lt;sklep-sms@noreply.github.com&gt;; Wysłane: 23:18 Sobota 2018-12-29Temat: Re: [gammerce/sklep-sms] Błąd przy instalacji. (#29)@Ne3kk powiedz czy wersja 3.6.5 rozwiązuje Twój problem



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.



2018-12-29 23:34: {
    "message": "Class Install\\DatabaseMigration does not exist",
    "file": "\/web1\/web1\/home\/karol13\/717631\/vendor\/illuminate\/container\/Container.php",
    "line": 788,
    "code": 0,
    "trace": [
        {
            "file": "\/web1\/web1\/home\/karol13\/717631\/vendor\/illuminate\/container\/Container.php",
            "line": 788,
            "function": "getClass",
            "class": "ReflectionParameter",
            "type": "->",
            "args": []
        },
        {
            "file": "\/web1\/web1\/home\/karol13\/717631\/vendor\/illuminate\/container\/Container.php",
            "line": 758,
            "function": "resolveDependencies",
            "class": "Illuminate\\Container\\Container",
            "type": "->",
            "args": [
                [
                    {
                        "name": "application"
                    },
                    {
                        "name": "migrationFiles"
                    },
                    {
                        "name": "databaseMigration"
                    }
                ]
            ]
        },
        {
            "file": "\/web1\/web1\/home\/karol13\/717631\/vendor\/illuminate\/container\/Container.php",
            "line": 608,
            "function": "build",
            "class": "Illuminate\\Container\\Container",
            "type": "->",
            "args": [
                "App\\ShopState"
            ]
        },
        {
            "file": "\/web1\/web1\/home\/karol13\/717631\/vendor\/illuminate\/container\/Container.php",
            "line": 575,
            "function": "resolve",
            "class": "Illuminate\\Container\\Container",
            "type": "->",
            "args": [
                "App\\ShopState"
            ]
        },
        {
            "file": "\/web1\/web1\/home\/karol13\/717631\/includes\/Middlewares\/IsUpToDate.php",
            "line": 18,
            "function": "make",
            "class": "Illuminate\\Container\\Container",
            "type": "->",
            "args": [
                "App\\ShopState"
            ]
        },
        {
            "file": "\/web1\/web1\/home\/karol13\/717631\/includes\/Kernels\/Kernel.php",
            "line": 66,
            "function": "handle",
            "class": "App\\Middlewares\\IsUpToDate",
            "type": "->",
            "args": [
                {
                    "attributes": {},
                    "request": {},
                    "query": {},
                    "server": {},
                    "files": {},
                    "cookies": {},
                    "headers": {}
                },
                {
                    "contextual": []
                }
            ]
        },
        {
            "file": "\/web1\/web1\/home\/karol13\/717631\/includes\/Kernels\/Kernel.php",
            "line": 30,
            "function": "runMiddlewares",
            "class": "App\\Kernels\\Kernel",
            "type": "->",
            "args": [
                {
                    "attributes": {},
                    "request": {},
                    "query": {},
                    "server": {},
                    "files": {},
                    "cookies": {},
                    "headers": {}
                }
            ]
        },
        {
            "file": "\/web1\/web1\/home\/karol13\/717631\/index.php",
            "line": 24,
            "function": "handle",
            "class": "App\\Kernels\\Kernel",
            "type": "->",
            "args": [
                {
                    "attributes": {},
                    "request": {},
                    "query": {},
                    "server": {},
                    "files": {},
                    "cookies": {},
                    "headers": {}
                }
            ]
        }
    ]
}
2018-12-29 23:35: {
    "message": "Class Install\\DatabaseMigration does not exist",
    "file": "\/web1\/web1\/home\/karol13\/717631\/vendor\/illuminate\/container\/Container.php",
    "line": 788,
    "code": 0,
    "trace": [
        {
            "file": "\/web1\/web1\/home\/karol13\/717631\/vendor\/illuminate\/container\/Container.php",
            "line": 788,
            "function": "getClass",
            "class": "ReflectionParameter",
            "type": "->",
            "args": []
        },
        {
            "file": "\/web1\/web1\/home\/karol13\/717631\/vendor\/illuminate\/container\/Container.php",
            "line": 758,
            "function": "resolveDependencies",
            "class": "Illuminate\\Container\\Container",
            "type": "->",
            "args": [
                [
                    {
                        "name": "application"
                    },
                    {
                        "name": "migrationFiles"
                    },
                    {
                        "name": "databaseMigration"
                    }
                ]
            ]
        },
        {
            "file": "\/web1\/web1\/home\/karol13\/717631\/vendor\/illuminate\/container\/Container.php",
            "line": 608,
            "function": "build",
            "class": "Illuminate\\Container\\Container",
            "type": "->",
            "args": [
                "App\\ShopState"
            ]
        },
        {
            "file": "\/web1\/web1\/home\/karol13\/717631\/vendor\/illuminate\/container\/Container.php",
            "line": 575,
            "function": "resolve",
            "class": "Illuminate\\Container\\Container",
            "type": "->",
            "args": [
                "App\\ShopState"
            ]
        },
        {
            "file": "\/web1\/web1\/home\/karol13\/717631\/includes\/Middlewares\/IsUpToDate.php",
            "line": 18,
            "function": "make",
            "class": "Illuminate\\Container\\Container",
            "type": "->",
            "args": [
                "App\\ShopState"
            ]
        },
        {
            "file": "\/web1\/web1\/home\/karol13\/717631\/includes\/Kernels\/Kernel.php",
            "line": 66,
            "function": "handle",
            "class": "App\\Middlewares\\IsUpToDate",
            "type": "->",
            "args": [
                {
                    "attributes": {},
                    "request": {},
                    "query": {},
                    "server": {},
                    "files": {},
                    "cookies": {},
                    "headers": {}
                },
                {
                    "contextual": []
                }
            ]
        },
        {
            "file": "\/web1\/web1\/home\/karol13\/717631\/includes\/Kernels\/Kernel.php",
            "line": 30,
            "function": "runMiddlewares",
            "class": "App\\Kernels\\Kernel",
            "type": "->",
            "args": [
                {
                    "attributes": {},
                    "request": {},
                    "query": {},
                    "server": {},
                    "files": {},
                    "cookies": {},
                    "headers": {}
                }
            ]
        },
        {
            "file": "\/web1\/web1\/home\/karol13\/717631\/index.php",
            "line": 24,
            "function": "handle",
            "class": "App\\Kernels\\Kernel",
            "type": "->",
            "args": [
                {
                    "attributes": {},
                    "request": {},
                    "query": {},
                    "server": {},
                    "files": {},
                    "cookies": {},
                    "headers": {}
                }
            ]
        }
    ]
}

**Comment by budziam** [comment]
"Class Install\DatabaseMigration does not exist" - brzmi jakbyś usunął folder install. Ten folder powinien zostać.

**Comment by Ne3kk** [comment]
Sprawdzę a token odblokowałeś?&nbsp;Od: "Michał Budziak" &lt;notifications@github.com&gt;Do: "gammerce/sklep-sms" &lt;sklep-sms@noreply.github.com&gt;; Wysłane: 23:55 Sobota 2018-12-29Temat: Re: [gammerce/sklep-sms] Błąd przy instalacji. (#29)"Class Install\DatabaseMigration does not exist" - brzmi jakbyś usunął folder install. Ten folder powinien zostać.

**Comment by Ne3kk** [comment]
Shop is up to date Taki bład do sklep nie moge wejść..&nbsp;Od: "meo" &lt;aaaa19988@interia.eu&gt;Do: "gammerce/sklep-sms" &lt;reply@reply.github.com&gt;; "gammerce/sklep-sms" ; Wysłane: 23:57 Sobota 2018-12-29Temat: Re: [gammerce/sklep-sms] Błąd przy instalacji. (#29)Sprawdzę a token odblokowałeś? Od: "Michał Budziak" &lt;notifications@github.com&gt;Do: "gammerce/sklep-sms" &lt;sklep-sms@noreply.github.com&gt;; Wysłane: 23:55 Sobota 2018-12-29Temat: Re: [gammerce/sklep-sms] Błąd przy instalacji. (#29)"Class Install\DatabaseMigration does not exist" - brzmi jakbyś usunął folder install. Ten folder powinien zostać.

**Comment by budziam** [comment]
Niestety, ale nic nie rozumiem z Twoich wiadomości. Napisz proszę bezpośrednio przez github, zamiast odpisywać na email, bo to chyba nie działa tak jak powinno.

**Comment by Ne3kk** [comment]
Owszem dziala,ale mam problem  chce wgrąć kopię bazy danych, usuwam tą nową wgrałem starą pisze błąd token wpisuej ten token i nadal to samo? Co zle robię?

**Comment by Ne3kk** [comment]
Poradziłem sobie inaczej usuwajac tylko zapis bazy graczy, dzieki mam nadzieje,ze  bedzie dzialać
Pozdrawiam

**Comment by Ne3kk** [comment]
Jeszcze mam znowu problem da się odzyskać hasło ktore sie zaklada przy instalacji do logowania jako admin w panel sklep jeśli tak to gdzie?

**Comment by budziam** [comment]
Możesz odzyskać hasło poprzez stronę /index.php?pid=forgotten_password
