### ISSUE TITLE
Zarządzanie grupami

### ISSUE THREAD

**Issue by dredek** [gammerce/sklep-sms#290]
Przydałoby się rozwinąć funkcjonalność grup w sklepie. Wiadomo jeśli jakaś z grup otrzyma dostęp do panelu z dostępem do zarządzania użytkownikami to może sobie ustawić grupę właściciela. Dobrym rozwiązaniem byłoby stworzyć grupę, która może ustawiać innym grupy z wyłączeniem tych z dostępem do panelu.

**Comment by budziam** [comment]
Słuszna uwaga, trzeba by ten problem jakoś rozwiązać. Co powiesz na takie podejście, że użytkownik może przypisać innym użytkownikom tylko te grupy, których uprawnienia nie są większe niż te które on sam posiada?

**Comment by budziam** [comment]
Funkcjonalność została zaimplementowana https://github.com/gammerce/sklep-sms/pull/292. Trzeba ją tylko jeszcze potestować. Niebawem wypuszczę nową, testową wersję sklepu, to będzie okazja przeklikać czy wszystko działa jak należy

**Comment by dredek** [comment]
> 
> 
> Słuszna uwaga, trzeba by ten problem jakoś rozwiązać. Co powiesz na takie podejście, że użytkownik może przypisać innym użytkownikom tylko te grupy, których uprawnienia nie są większe niż te które on sam posiada?

Wydaje mi się, że takie rozwiązanie powinno pomóc. W takim razie czekam niecierpliwie na aktualizacje sklepu.

**Comment by budziam** [comment]
Pojawiła się nowa wersja sklepu [3.16.3](https://github.com/gammerce/sklep-sms/releases/tag/3.16.3)
