### ISSUE TITLE
Problem ze skryptem/serwerem ogólnie z połączeniem się serwera ze skryptem na stronie.

### ISSUE THREAD

**Issue by StrajGer** [gammerce/sklep-sms#294]
**Opis problemu**
Witam raz jeszcze, dzisiaj znalazłem chwilke czasu żeby przysiąść i podpiąć sklep do serwera w 1.6, wszystko skonfigurowane zgodnie z instrukcjami, natomiast po wpisaniu /sklepsms otrzymuje komunikat o pojawieniu się błędów, no to sprawdziłem logi, okazało się, że serwer nie może połączyć się z serwerem www (error 500) - tak jest w logach po stronie serwera 1.6, nie mam pojęcia czyten problem występuje po stronie serwera, czy samego skryptu, nie mam jak tego sprawdzić (nie mam drugiego serwera www do testów), także bardzo bym prosił o sprawdzenie przez autora skryptu czy aby skrypt www nie wywala błędu przy próbie otrzymania "kontaktu" ze strony serwera gry.

/Edit, usunięta wzmianka o błędzie 402 żeby nikogo nie myliło.

**Szczegóły (proszę, wypełnij poniższe informacje)**
 - Czego dotyczy problem: Raczej skrypt strony
 - Wersja strony WWW: Najnowsza, 3.16.2
 - Wersja pluginu: 3.11.3

**Comment by StrajGer** [comment]
Log po stronie serwera www przy próbie wywołania skryptu przez serwer gry:
`"GET /shop16/api/server/config?token=XXXXX&version=3.11.3&language=english HTTP/1.1" 500 4001 "-" "amxmodx"`

**Comment by StrajGer** [comment]
Dobra, ten błąd 402 to akurat jest spowodowany moją przeglądarką (Brave) natomiast na google chrome po wpisaniu prawidłowego tokena wyskakuje coś takiego: "Server unauthorized" i rozumiem, że to jest zabezpieczenie kiedy link nie zostanie wywołany z tagiem "amxmod", usuwałem jeszcze https z linku ale zmieniło to błąd 500 na 301.

**Comment by StrajGer** [comment]
Dokładniej mam ten błąd:
L 02/19/2021 - 18:41:02: Invalid server config response HTTP code [500]
L 02/19/2021 - 18:41:02: Error 23 - Wystąpił błąd podczas ładowania konfiguracji serwera.

**Comment by StrajGer** [comment]
Kiedyś ten skrypt był prostszy, łączyło się z bazą danych od sklepu i po problemie, a teraz wszystko wywoływane jest przez skrypt na stronie, sprawdzałem jeszcze konfiguracje i u siebie niczego złego nie widzę, ktoś wcześniej też miał podobny problem i pisał o portach, tylko szkoda, że nie napisał o jakie porty dokładnie chodzi to bym sobie je ewentualnie ręcznie odblokował przez iptables -.-.

**Comment by budziam** [comment]
Serwer otrzymuje blad http 500, co oznacza, że jest problem po stronie strony WWW. W katalogu data/logs/errors.log powinno być więcej informacji.

Czy mógłbyś proszę podać adres WWW swojego sklepu?

**Comment by StrajGer** [comment]
> Serwer otrzymuje blad http 500, co oznacza, że jest problem po stronie strony WWW. W katalogu data/logs/errors.log powinno być więcej informacji.
> 
> Czy mógłbyś proszę podać adres WWW swojego sklepu?

https://fraglife.pl/shop16/

**Comment by StrajGer** [comment]
https://pastebin.com/dzY1aZYM tutaj masz cały errors.log.

**Comment by StrajGer** [comment]
Dodam jeszcze, że do serwera www zapytanie dochodzi, tylko nwm skąd ten błąd 500, mam jeszcze jeden sklep do go, działa on troche inaczej, ale tez używa skryptu ze strony i jakoś działa.

**Comment by StrajGer** [comment]
a i w tych logach jak coś chcesz bardziej szczegółowo, to data dzisiejsza czyli 19.02 i godzina od 18stej, 18:40 tam sie chyba zaczyna log kiedy użyłem komendy /sklepsms na serwerze.

**Comment by StrajGer** [comment]
Nie wiem czy dobrze myśle bo się tak średnio znam, ale z tego co widze w logach + ma to potwierdzenie w acp bo jak wejde we flagi użytkowników to wywala błąd właśnie też 500 i pokazuje w pliku z logami, że nie ma tabeli "ss_players_flags" i fakt, kiedy wejde w baze danych to jej tam nie ma, ale to już jest na 100% wina wtedy twojego skryptu bo nie ma w nim kodu odpowiedzialnego za tworzenie tej tabeli, jak robiłem instalacje to normalnie przeszło bez żadnych błędów. Nie wiem czy to ma jakiś związek, ale widze, że w tych błędach też jest coś o flagach a dodatkowo w pliku serverconfigcontroller.php też jest jakaś linijka do sprawdzania flag, może dlatego się wykrzacza.

**Comment by StrajGer** [comment]
Jakieś brednie we wcześniejszym komentarzu napisałem więc go skasowałem żeby nie wprowadzać w błąd.

**Comment by StrajGer** [comment]
Dobra, ogarnąłem, problem był w bazie danych z tabelą "ss_players_flags" musiałem ją usunąć i wzorując się na starym zrzucie z tej bazy "wkleić" ją od nowa przez zapytanie sql, tylko nie wiem czy jest dobra składnia, dlatego gdybyś mógł, to podeślij mi zrzut tej tabeli + nie wiem czy to jest wina mojej bazy czy twojego skryptu, ale korzystam z bazy danych pukawki, rok temu też instalowałem na niej twój sklep więc tak nie sądze, żeby to przez baze na pukawce się działo, sprawdź swój skrypt bo możesz mieć poważny problem ze strukturą tej tabeli podczas instalacji, zainstaluj u siebie sklep od nowa i jak chcesz zobaczyć z miejsca czy ten błąd wystąpi to po instalacji wejdź w baze danych i spróbuj otworzyć przez phpmyadmin te tabele, jeżeli wywali ci błąd przy samej próbie otwarcia to oznacze, że gdzieś wkradł się błąd w twój skrypt.

**Comment by StrajGer** [comment]
Teraz jest inny problem po wpisaniu kodu który wygenerowałem, ""message": "Return value of App\\ServiceModules\\ExtraFlags\\PlayerFlagRepository::create() must be an instance of App\\ServiceModules\\ExtraFlags\\PlayerFlag, null returned"," coś jest nieźle powalone.

**Comment by StrajGer** [comment]
no i odkryłem następny problem, w pliku includes/ServiceModules/ExtraFlags/PlayerFlagRepository.php w dwóch linijkach gdzie jest "PlayerFlag" brakowało ? przed PlayerFlag czyli "?PlayerFlag" i to już jest ewidetnie problem po stronie twojego skryptu i mam nadzieje, że przedłużysz mi licencje bo troche czasu poszło ;/

**Comment by budziam** [comment]
Cześć @StrajGer,
dawno się nie odzywałem. Widzę, że bardzo dużo problemów udało ci się naprawić. Doładowałem twoje konto na stronie sklep.sklep-sms.pl kwotą 80zł w podziękowaniu za twój wysiłek i żeby jakoś ci zrekompensować to że tak długo się nie odzywałem.

Jeżeli chodzi o ten błąd
```
Return value of App\ServiceModules\ExtraFlags\PlayerFlagRepository::create() must be an instance of App\ServiceModules\ExtraFlags\PlayerFlag, null returned
```
to przyjrzę się temu i spróbuję zrozumieć skąd się ten błąd bierze. Nie powinno być tak, że ta metoda zwraca wartość `null` zamiast obiektu typu `PlayerFlag`.

**Comment by StrajGer** [comment]
> Cześć @StrajGer,
> dawno się nie odzywałem. Widzę, że bardzo dużo problemów udało ci się naprawić. Doładowałem twoje konto na stronie sklep.sklep-sms.pl kwotą 80zł w podziękowaniu za twój wysiłek i żeby jakoś ci zrekompensować to że tak długo się nie odzywałem.
> 
> Jeżeli chodzi o ten błąd
> 
> ```
> Return value of App\ServiceModules\ExtraFlags\PlayerFlagRepository::create() must be an instance of App\ServiceModules\ExtraFlags\PlayerFlag, null returned
> ```
> 
> Bierze się on stąd, że w twoim query tworzącym tabelę `ss_players_flags` nie zdefiniowałeś tzw. `primary key`. Co spowodowało, że podczas tworzenia nowego wiersza w tej tabeli, nie jest ustawiana wartość w kolumnie `id`.
> 
> Odpowiednie zapytanie tworzące tą tabelę możesz znaleźć tutaj:
> 
> * https://github.com/gammerce/sklep-sms/blob/master/migrations/2018_01_14_230340_init.sql#L567
> * https://github.com/gammerce/sklep-sms/blob/master/migrations/2020_01_24_233600_auth_data_utf8_mb4_compliant.php#L12
> * https://github.com/gammerce/sklep-sms/blob/master/migrations/2020_05_11_215500_change_foreign_column_names.php#L19
> * https://github.com/gammerce/sklep-sms/blob/master/migrations/2020_04_21_175000_utf8mb4_unicode.php#L12

Dzięki za informacje, póki co, ze względu na ostatni pożar serwerowni ovh straciłem praktycznie wszystkie swoje serwery, więc robie sobie przerwe, zapewne jak kiedyś wróce, to użyje tych 80 zł na zakup nowej licencji. :)

Pozdrawiam!
