### ISSUE TITLE
Problem podczas aktualizacji strony www sklepu do najnowszej wersji.

### ISSUE THREAD

**Issue by Roughster62** [gammerce/sklep-sms#299]
Witam,

Pobrałem paczkę pod PHP 8.0, następnie podmieniłem zawartość.

Teraz po wejściu na stronę sklepu: https://sklep.cs-jastrzebie.pl wyświetla się error:

Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' in /home/klient/csjastrz/sklep.cs-jastrzebie.pl/includes/functions.php on line 659

Mogę prosić o poprawkę?

**Comment by budziam** [comment]
Cześć,
sklep na stronie https://demo.sklep-sms.pl/ działa na serwerze z PHP w wersji 8.0.3. Wersja sklepu to [3.16.3](https://github.com/gammerce/sklep-sms/releases/tag/3.16.3) Stąd też wydaje mi się, że problem gdzieś indziej może leżeć niż w sklepie. Jesteś pewien, że sklep jest obsługiwany przez PHP 8.0?

W pliku `functions.php` w linii 659 znajduje się taki kawałek kodu
```
        ->filter(fn($permission) => $permission)
```

Korzysta to z funkcjonalności arrow functions (https://www.php.net/manual/en/functions.arrow.php) wprowadzonej do PHP w wersji 7.4. Stąd też zgaduję, że wersja PHP na której stoi sklep musi być starsza niż 7.4
