### ISSUE TITLE
Problem z aktualizacją sklepu na stronie www z (v3.13.0) do (v3.16.3).

### ISSUE THREAD

**Issue by KuczoR** [gammerce/sklep-sms#300]
Witam,
Poprałem z repozytorium paczkę plików pod PHP 5.6, następnie podmieniłem wszystko na serwerze ftp.
Po wejściu na stronę sklepu: http://ciemna.pl/Forum/sklepsms/ wyskoczył monit z aktualizacją sklepu i wszystko zaznaczone na OK, czyli aktualizacja powinna przejść bez problemów lecz gdy kliknąłem aby wykonać aktualizację to niestety nie powiodła się.
I sklep utworzył error.log oraz się zablokował.
Po przywróceniu kopii zapasowej bazy danych sklepu i plików na ftp sklep z powrotem działa na starej wersji poprawnie, lecz w panelu admina wyświetla się monit o dostępnej aktualizacji sklepu WWW, gdy go teraz nacisnę wyświetla się "Skrypt sklepu jest zaktualizowany do najnowszej wersji."
Tyle że skrypt sklepu jest przywrócony do wersji v3.13.0 a nie do najnowszej v3.16.3.
Spróbowałem dla testu zainstalować sklep z paczki którą pobrałem w innej ścieżce i bazie danych od nowa i wszystko działa jak należy tyle tylko że potrzebuję zaktualizować istniejący sklep tak aby gracze nie stracili swoich wykupionych usług oraz ja całej konfiguracji itp. W załączniku załączam error.log. Proszę o pomoc.
[errors.log](https://github.com/gammerce/sklep-sms/files/6212235/errors.log)
![error](https://user-images.githubusercontent.com/50302363/112642761-ec19d100-8e43-11eb-8a5e-008013efb32a.png)

**Comment by budziam** [comment]
Cześć,
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'p516063_mybb.ss_service_codes' doesn't exist`
```
Z powyższego błędu wnioskuję, że z jakiegoś powodu w bazie twojego sklepu nie ma tabeli `ss_service_codes`, która powinna tam być. Z tego powodu aktualizacja sklepu nie powiodła się. Możemy spróbować utworzyć tą tabelę i może aktualizacja przejdzie. Chociaż podejrzewam, że w bazie mogą być jeszcze inne problemy i aktualizacja zatnie się na czymś innym. 

Jeżeli chcesz, to mogę ręcznie przeprowadzić aktualizację twojego sklepu. Potrzebowałbym tylko dostęp do FTP oraz bazy danych.

**Comment by KuczoR** [comment]
Dziękuję za chęć pomocy, zainstalowałem sklep pod innym katalogiem i trochę się pomęczyłem ale udało mi się ręcznie przenieść dane z starej bazy danych do nowej. Fakt trwało to około 6 godzin ale się udało, pozdrawiam.  
            
          
     
      
       
        Dnia 30 marca 2021 15:39 Michał Budziak ***@***.***&gt; napisał(a):
       
    
       
         
 Cześć, 
 SQLSTATE[42S02]: Base table or view not found: 1146 Table &#39;p516063_mybb.ss_service_codes doesn&#39;t exist`
 
 Z powyższego błędu wnioskuję, że z jakiegoś powodu w bazie twojego sklepu nie ma tabeli  ss_service_codes , która powinna tam być. Z tego powodu aktualizacja sklepu nie powiodła się. Możemy spróbować utworzyć tą tabelę i może aktualizacja przejdzie. Chociaż podejrzewam, że w bazie mogą być jeszcze inne problemy i aktualizacja zatnie się na czymś innym. 
 Jeżeli chcesz, to mogę ręcznie przeprowadzić aktualizację twojego sklepu. Potrzebowałbym tylko dostęp do FTP oraz bazy danych.
