### ISSUE TITLE
API MICROSMS error.

### ISSUE THREAD

**Issue by lyskaczu** [gammerce/sklep-sms#31]
Witam, tak jak w temacie, przy konfiguracji API pod MICROSMS napotkałem mały ale kluczowy problem, mianowicie numery na które nalezy wysyłac smsy sie nie zgadzają. Poniżej zamieszczam screeny.

SKLEP:
https://scr.hu/222Jg9l

PANEL MICROSMS:
https://scr.hu/3OOGWM0

Dodatkowo przy próbie płatności przelewem przez MICROSMS otrzymuje komunikat od api 
Podpis transakcji wykonany nieprawidłowo.
Dzięki za aktualizacje.

**Comment by budziam** [comment]
Cześć,
dzięki za zgłoszenie błędu

Niebawem poprawię kody sms i wypuszczę aktualizację sklepu.
Co do płatności internetowych należy ustawić `Typ kodowania` na wartość `sha256`. Dodałem informację o tym we wpisie dotyczącym konfiguracji płatności MicroSMS: https://github.com/gammerce/sklep-sms/wiki/Konfiguracja-p%C5%82atno%C5%9Bci-MicroSMS

**Comment by lyskaczu** [comment]
Dokładnie tak jak piszesz płatności przelewem działają poprawnie wystarczyło zmienić kodowanie w panelu MICRO, z gory dzięki za aktualizację SMS API.
