### ISSUE TITLE
messagemode po aktualizacji cs Steam 2019

### ISSUE THREAD

**Issue by xdbxpr** [gammerce/sklep-sms#33]
Nie można wpisać hasła do nicku, ani kodu zwrotnego poprzez messagemode (oczywiście tylko po stronie Steam).

**Comment by budziam** [comment]
Cześć,
dzięki za informację. Postaram się na dniach wypuścić aktualizację.

**Comment by budziam** [comment]
Z tego co mi wiadomo steam cofnął aktualizację, więc wszystko powinno działać.
