### ISSUE TITLE
błąd raczej nie ale problem

### ISSUE THREAD

**Issue by AnubisZMC** [gammerce/sklep-sms#333]
Witam. jedni mogą brać to jako błąd drudzy jako problem a ja biorę za nie rozważność... kiedyś bez problemu można było znaleźć o jakie pliki tu chodzi a teraz??

![image](https://user-images.githubusercontent.com/91164686/134261254-4b90e9cc-f87b-45ef-b597-6c908f4cc2b9.png)

piszę tu bo gdzie napisze to 0 odpowiedzi

a więc jakie to pliki mają mieć te uprawnienia?

**Comment by AnubisZMC** [comment]
jakie to pliki mają mieć te uprawnienia?

**Comment by budziam** [comment]
Cześć,
lista tych plików może ulec zmianie w kolejnych wersjach sklepu, dlatego też nie jest wypisana w dokumencie konfiguracja sklepu. Znajduje się ona jednak na stronie instalatora sklepu
![image](https://user-images.githubusercontent.com/10908895/136861031-0763a6fa-8cc8-4e95-80b0-0dcd56eb47c5.png)

**Comment by budziam** [comment]
Zachęcam do wykupienia licencji wraz z hostingiem aby nie musieć się przejmować problemami konfiguracji. Więcej informacji można znaleźć na https://sklep-sms.pl/#cloud
