### ISSUE TITLE
3.17.0 aktualiazacja

### ISSUE THREAD

**Issue by Burek-afk** [gammerce/sklep-sms#334]
wgralem nowe pliki na ftp i sklep nie dziala.
zrobilem reset hostingu i wgralem nowe pliki i wyskakuje:

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)' in /web1/web1/home/burrows/254207/includes/Support/Database.php:63 Stack trace: #0 /web1/web1/home/burrows/254207/includes/Support/Database.php(63): PDO->__construct('mysql:host=;por...', '', '', Array) #1 /web1/web1/home/burrows/254207/includes/Support/Database.php(47): App\Support\Database->connectWithoutDb() #2 /web1/web1/home/burrows/254207/includes/Support/Database.php(92): App\Support\Database->connect() #3 /web1/web1/home/burrows/254207/includes/Repositories/ServiceRepository.php(24): App\Support\Database->query('SELECT * FROM `...') #4 /web1/web1/home/burrows/254207/includes/Theme/EditableTemplateRepository.php(50): App\Repositories\ServiceRepository->all() #5 /web1/web1/home/burrows/254207/includes/Theme/EditableTemplateRepository.php(30): App\Theme\EditableTemplateRepository->listInner() #6 /web1/web1/home/burrows/254207/includes/Theme/EditableTemplateRepository.php(42): in /web1/web1/home/burrows/254207/includes/Support/Database.php on line 63

**Comment by AnubisZMC** [comment]
mam ten sam problem od ponad tygodnia i właściciel sklep-sms.pl ma na to wy*****e olewa emaile i posty :/

**Comment by Burek-afk** [comment]
Problem rozwiązałem, zrobiłem wersje 3.16 nie bede czekal

**Comment by budziam** [comment]
Cześć,
zalecam aktualizację do wersji 3.18
