### ISSUE TITLE
Komunikaty na serwerze

### ISSUE THREAD

**Issue by Burek-afk** [gammerce/sklep-sms#337]
1.Przy zakupie uslugi wyskakuje okno motd gdzie nie ma polskich znakow tylko znaki zapytania, gdzie to zmienic?

2. type_setinfo ustawione jest na setinfo _ss a powinno setinfo _pw

**Comment by AnubisZMC** [comment]
zrobiłem tak jak ty że za instalowałem wersjie 3.16 i też miałem ten problem z setinfo zrób aktualizacje do 3.17.0 nic ci się nie popsuje a będziesz miał najnowszą wersje sklepu i wszystko działa poprawnie :)
