### ISSUE TITLE
Brak treści sms pod komendą /sklepsms

### ISSUE THREAD

**Issue by dredek** [gammerce/sklep-sms#338]
Po wpisaniu komendy /sklepsms i wybraniu usługi w celu jej zakupienia nie wyświetla treści SMS.
Niżej zamieszczam screenshota. Problem pojawił się jakoś teraz na dniach.
https://prnt.sc/1ursmlb

Problem dotyczy pluginu amxx co można wywnioskować po screenshocie. Wersja strony najnowsza, wersja pluginu 3.11.3.

Zaskakujące jest to że z dnia na dzień taki problem występuje. Liczę na szybką reakcje.

**Comment by dredek** [comment]
Dodam również, że po stronie WWW również nie wyświetla treści SMS dla płatności cssetti.

**Comment by dredek** [comment]
Problem rozwiązany. Przyczyną był hosting pukawki:
"Występował tutaj problem związany z poprawnym odczytem certyfikatu strony cssetti, problem rozwiązany"

**Comment by budziam** [comment]
Cieszę się, że udało się szybko naprawić problem. Wątek zamykam.
