### ISSUE TITLE
Bug uprawnień 

### ISSUE THREAD

**Issue by Weakus** [gammerce/sklep-sms#34]
W sumie to ten bug jest już dłuższy czas, a nawet od początku. Przy nadawaniu usługi przez ACP i zaznaczając opcje "Na zawsze" to graczowi przyznawane są full uprawnienia (root), oczywiście mówię tutaj o SourceMod'ie, nie wiem jak przy AMXX'ie.

Fix?

**Comment by budziam** [comment]
Cześć,
niebawem planuję popracować nieco nad pluginiem pod SourceMod. Postaram się rozwiązać również ten problem.

Jeżeli uda mi się ruszyć z tematem, to dam tutaj o tym znać.

**Comment by budziam** [comment]
@Weakus udało mi się znaleźć przyczynę tego problemu. Postaram się po majówce wypuścić poprawkę, a może nawet uda się przed  ;)

**Comment by Weakus** [comment]
No nic. Nic tylko czekać na update :)

**Comment by budziam** [comment]
Jest nowa wersja pluginu pod serwery sourcemod. Poza poprawką o którą prosiłeś jest jeszcze kilka zmian: https://github.com/gammerce/plugin-sourcemod/releases/tag/3.5.0
Gdyby coś nie działało, pisz proszę tutaj :)

**Comment by Weakus** [comment]
Warto też dodać informacje, w której będą zawarte informacje dot. system2. Nie ukrywam, że troszeczkę szukałem plików.

PS. Na obecną chwilę nie widzę błędów.

**Comment by budziam** [comment]
A jakich plików musiałeś szukać? W paczce jest dodany plik `system2.so` w katalogu `extensions`

**Comment by Weakus** [comment]
L 05/02/2019 - 01:49:45: [System2] File 'ca-bundle.crt' is missing in 'sourcemod/data/system2/' folder, please install it

W paczce tego nie ma.

**Comment by KuczoR** [comment]
Błąd w logach, losowo wyskakuje, czasem co mapę czasem co dwie...
L 05/05/2019 - 20:29:50: [shopsms.smx] Error: 204. Wystąpił błąd podczas wczytywania usług graczy.
Po aktualizacji stare vipy są a nowi gracze kupują i nie dostają uprawnień choć w czasowych usługach graczy nowi użytkownicy się dodają. Jak to naprawić?

**Comment by KuczoR** [comment]
> 
> 
> L 05/02/2019 - 01:49:45: [System2] File 'ca-bundle.crt' is missing in 'sourcemod/data/system2/' folder, please install it
> 
> W paczce tego nie ma.

No chyba o czymś zapomniał autor sklepu, już nie pierwszy raz...
Proszę: https://forums.alliedmods.net/showthread.php?t=146019

**Comment by KuczoR** [comment]
Mam pytanie, jest możliwość zakupu dożywotniej licencji? zakupowanej jednorazowo?
Byłbym chętny bo szczerze mówiąc pilnowanie kończącej się licencji mnie dobija, oczywiście mowa tu o normalnej kwocie nie takiej jak za przedłużenie :)

**Comment by Weakus** [comment]
> > L 05/02/2019 - 01:49:45: [System2] File 'ca-bundle.crt' is missing in 'sourcemod/data/system2/' folder, please install it
> > W paczce tego nie ma.
> 
> No chyba o czymś zapomniał autor sklepu, już nie pierwszy raz...
> Proszę: https://forums.alliedmods.net/showthread.php?t=146019

Czytaj uważnie to co pisze. Napisałem, że troszkę szukałem tego, więc znalazłem. Post zbędny. Temat dotyczy czegoś innego, więc załóż swój i cierpliwie czekaj.

**Comment by budziam** [comment]
Dzięki za zwrócenie uwagi, dodam ten plik przy następnej aktualizacji pluginu. Z tego co widzę, to wszystko działa prawidłowo bez tego pliku, tylko w konsoli pojawia się ten warning.

@KuczoR nie ma możliwości zakupu licencji na zawsze. Możesz natomiast przedłużyć licencję na 2 lata.
