### ISSUE TITLE
Błąd przy instalacji sklepu

### ISSUE THREAD

**Issue by cocaocla** [gammerce/sklep-sms#342]
Podczas instalacji sklepu wyskakuje biała strona zamiast instalatora Licencja leci a sklepu brak
Sklep pod adresem: sklep.quailitystrike.com
![image](https://user-images.githubusercontent.com/57010926/142015189-0815bf83-93a1-4dab-a608-4d5e53788651.png)
**Szczegóły (proszę, wypełnij poniższe informacje)**
 - Czego dotyczy problem: strona www
 - Wersja strony WWW: php 7.4 mysql 7.4
 - Wersja pluginu: Najnowsza ze strony.

**Comment by budziam** [comment]
Cześć,
sklep sms domyślnie nie współpracuje poprawnie z nginx. Wymaga odpowiedniej konfiguracji, którą można stworzyć bazując na: https://github.com/gammerce/sklep-sms/blob/master/docker/vhost.conf

Najłatwiej jednak jest wykupić licencję wraz z hostingiem i nie musieć się przejmować tą całą konfiguracją. Więcej informacji można znaleźć na https://sklep-sms.pl/#cloud
