### ISSUE TITLE
Nie otrzymałem token

### ISSUE THREAD

**Issue by kolorek12** [gammerce/sklep-sms#348]
**Opis problemu**
Zakupiłem licencje, opłaciłem i nie otrzymałem tokenu. 

**Oczekiwane zachowanie**
Wysłanie tokenu :)

**Szczegóły (proszę, wypełnij poniższe informacje)**
 - Czego dotyczy problem: Wszystko
 - Wersja strony WWW: php 7.1

**Comment by kolorek12** [comment]
Długo jeszcze mam czekać ? Mam nadzieję, że okres będzie liczony od czasu wydania tokenu bo nie raczycie nawet odpisać na maile

**Comment by budziam** [comment]
Cześć,
sprawa została wyjaśniona na mailu.
