### ISSUE TITLE
Licencja sklep-sms.pl - nie działające sklepy

### ISSUE THREAD

**Issue by Vakos321575** [gammerce/sklep-sms#351]
https://license.sklep-sms.pl/v1/authorization/web?fbclid=IwAR2BUHGb5soByuC7W7DbfTK36mo0oDPTaOZku0vPkPgH4DADLGe63GiIgPs
https://license.sklep-sms.pl/?fbclid=IwAR12n2MEYrOw8P-r9cUEnIpNs_6cR4c1B-8dABfJhS66RgSb_J3AuarRi9Q

Jak widać strona licencji poszła w pizdu i żadne sklepy nie działają. Do naprawy w trybie natychmiastowym @budziam

**Comment by budziam** [comment]
Cześć,
błąd wynikał z drobnej awarii technicznej, która trwała od 22:50 - 00:30. Czasami takie rzeczy niestety są nie do uniknięcia. Przepraszam za wszelkie niedogodności.
