### ISSUE TITLE
Update 3.4.0 to 3.5.0

### ISSUE THREAD

**Issue by KuczoR** [gammerce/sklep-sms#36]
Witam.
Zwracam się z prośbą o pomoc dotyczącą sklepu sms.
Od dawna mam wykupioną licencję na sklep, w wersji 3.4.0 na sockets wszystko działało ok, po wymaganej aktualizacji do wersji 3.5.0 system2 sklep przestał współpracować, stare vipy z sklepu przed aktualizacją odczytuje normalnie i na serwerze gracze je posiadają a nowo zakupione vipy po zakupie dodają się niby do sklepu i bazy ale na serwerze już ich nie ma (stare vipy  są, nowe nie) w logach wyskakuje błąd losowo co mapę nie raz co dwie: L 05/05/2019 - 23:04:37: [shopsms.smx] Error: 204. Wystąpił błąd podczas wczytywania usług graczy. Details: Lost connection to MySQL server during query.
Tyle że usługi chyba wczytuje bo stare vipy są?! 
Biblioteka System2 na serwerze uruchomiona poprawnie...
Co najlepsze po aktualizacji dalej wyświetla na www sklepu że posiadam wersję 3.4.0... pobierałem kilka razy wersję dla swojego sourcemoda 1.8.0 i dalej to samo więc wykluczam błąd przy pobieraniu.
Stara wersja 3.4.0 odkąd wyszła aktualizacja 3.5.0 magicznie przestała działać i po głosowaniu na mapę crashuje serwer dlatego nie mogę jej dalej używać, a szkoda bo z nią problemów nie miałem.

**Comment by budziam** [comment]
Cześć,
jeżeli pojawia się błąd: `Lost connection to MySQL server during query`, to bardzo dziwne, że jakiekolwiek usługi się wczytują. Może te usługi, które się wczytują pochodzą z `sourcebans` albo innego systemu nadającego uprawnienia? Wersja pluginu nie aktualizuje sie w panelu admina, bo pewnie serwer nie jest w stanie wykonać zapytania do bazy mysql.

Co do crashowania się serwera przy wersji `3.4.0` - jesteś w stanie podać treść błędu, która się pojawia?

Sam błąd `Lost connection to MySQL server during query` brzmi bardzo jakby to był problem z bazą. Zdziwiłbym się, gdyby system2 miał tutaj coś do rzeczy.
