### ISSUE TITLE
Zawirusowana aktualizacja sklepu

### ISSUE THREAD

**Issue by dredek** [gammerce/sklep-sms#362]
Podczas pobierania wersji do aktualizacji z tego linku:
https://github.com/gammerce/sklep-sms/releases/tag/3.18.0
Wersja 5.6, za każdym razem antywirus informuje o wykryciu trojana a konkretnie: Trojan:Script/Ulthar.A!ml. 
Sama aplikacja windows defender już blokuje pobranie pliku. Czy to będzie poprawione czy mam sobie odpuścić aktualizacje sklepu?
Myślę, że nie muszę tłumaczyć jak ten wirus działa, ale wiem jedno. Taka sytuacja nie powinna mieć miejsca zwłaszcza, że spora ilość osób korzysta ze skryptu.

**Comment by budziam** [comment]
Cześć,
tutaj można znaleźć przeskanowaną aktualizację dla php 8.0 https://www.virustotal.com/gui/file/5dd88ac7d2d5c085ec05b49a62f6dd96d3b094a40315bf0e13bd57f402f24d3e?nocache=1 Defender ma jakiś problem z tym archiwum, ale niewiele mogę z tym zrobić.

**Comment by dredek** [comment]
Możesz podesłać wersje dla php 5.6?

**Comment by dredek** [comment]
Okej już nieważne. Aktualnie nie wykrywa wirusa więc problem został rozwiązany.
