### ISSUE TITLE
Segmentation Fault - nickname mail

### ISSUE THREAD

**Issue by dredek** [gammerce/sklep-sms#364]
Krótko i na temat. Serwer crashuje z powodem Segmentation Fault podczas, gdy dana osoba zakupi usługę na nick + hasło, wpisując adres email w rubryce nick przykładowo u mnie do problemu dochodziło, gdy osoba zakupiła usługę na nick:
kacper.xxxxx@onet.eu

**Comment by dredek** [comment]
Dodatkowo dodam, że na wersji 1.8.2 jest problem z Segmentation Fault, podczas gdy ktoś zakupi usługę na nick ze specjalnymi znakami. W takiej sytuacji wywala serwer, póki usługa nie zostanie usunięta po stronie WWW, to serwer nie wstanie. Proszę o poprawę plików oraz wrzucenie aktualizacji tak by wszystko poprawnie funkcjonowało.

**Comment by budziam** [comment]
@dredek czy znaki specjalnie można wpisać tylko poprzez stronę WWW, czy podczas zakupu przez serwer to również jest możliwe?
