### ISSUE TITLE
Przeglądanie Cennika

### ISSUE THREAD

**Issue by dredek** [gammerce/sklep-sms#365]
Dodać możliwość dodania uprawnienia do przeglądania cennika dla danej grupy.

**Comment by budziam** [comment]
@dredek tylko przeglądanie, czy możliwość tworzenia/usuwania/edycji cen również?

**Comment by budziam** [comment]
Dodałem oba uprawnienia, zarówno do przeglądania jak i zarządzania cennikiem. Nowa funkcjonalność została już wgrana do wszystkich sklepów korzystających z rozwiązania w chmurze. Niebawem powinna pojawić się nowa wersja sklepu, która będzie zawierać tą funkcjonalność.
