### ISSUE TITLE
usługa vip

### ISSUE THREAD

**Issue by mikihere** [gammerce/sklep-sms#37]
Zakupiłem usługę Vip (wysyłajac sms) otrzymałem kod,kod byl poprawny a zakupiona usługa działała chwilowo-wykupiłem na 1-msc a po 20 minutach znika mi usługa,prosze o jak najżybsze załatwienie sprawy

**Comment by budziam** [comment]
Cześć,
myślę, że powinieneś to zgłosić do właściciela sieci w której dokonałeś zakupy usługi :)
