### ISSUE TITLE
SteamID64 - kupno usług

### ISSUE THREAD

**Issue by Vakos321575** [gammerce/sklep-sms#371]
Cześć.
Proponuję dodać możliwość do kupna usługi na SteamID aby sklep www, gdy ktoś poda SteamID64 automatycznie przekonwertował sobie to na normalny SteamID serwerowy - zmiana głównie tyczy się CS:GO ale można by było wprowadzić to ogólnie.

Wtedy zakładka może być podpisana SteamID / SteamID64 i można podawać wtedy normalny SID (STEAM_) lub SteamID64 (5213515...)

**Comment by budziam** [comment]
Cześć,
podoba mi się ten pomysł. Postaram się to zaimplementować w niedalekiej przyszłości.

**Comment by budziam** [comment]
@Vakos321575 funkcjonalność została zaimplementowana i jest już dostępna dla klientów korzystających ze sklepu w chmurze. Możesz ją przetestować tutaj: https://demo.sklep-sms.cloud/
