### ISSUE TITLE
Unit tests require database access?

### ISSUE THREAD

**Issue by Danon** [gammerce/sklep-sms#378]

**Comment by budziam** [comment]
Feel free to suggest appropriate changes

**Comment by budziam** [comment]
Done. You can run unit tests using `make test:unit` command https://github.com/gammerce/sklep-sms/pull/379

**Comment by Danon** [comment]
![image](https://user-images.githubusercontent.com/13367735/169707456-d76145c8-96c5-42c8-a621-a5940edfc627.png)
