### ISSUE TITLE
Nie działają usługi po zaktualizowaniu pluginu sourcemod 11

### ISSUE THREAD

**Issue by blady334** [gammerce/sklep-sms#398]
Zaktualizowałem plugin sklepu do najnowszej wersji SOURCEMOD 11.
Nie wczytuje usług ludzi, którzy zakupili (np. VIP).
W logach wywala taką treść:
L 10/22/2022 - 13:10:12: [SM] Blaming: shopsms.smx
L 10/22/2022 - 13:10:12: [SM] Call stack trace:
L 10/22/2022 - 13:10:12: [SM]   [1] Line 270, include/shopsms/server::ExtractPlayersFlags
L 10/22/2022 - 13:10:12: [SM]   [2] Line 158, include/shopsms/server::Server_LoadConfigCallback
L 10/22/2022 - 13:32:47: [SM] Exception reported: Array index out-of-bounds (index 26, limit 26)

**Comment by budziam** [comment]
Cześć,
postaram się dzisiaj na to spojrzeć

**Comment by budziam** [comment]
Wersja [3.12.1](https://github.com/gammerce/plugin-sourcemod/releases/tag/3.12.1) powinna naprawiać ten błąd

**Comment by Vakos321575** [comment]
shopsms_const.inc:
`#define VERSION "3.11.1"`

Sklep po aktualizacji nadal widzi wersję 3.11.1 zapewne, gdyż w include nie było zaktualizowane.

**Comment by budziam** [comment]
@Vakos321575 w wersji [3.12.2](https://github.com/gammerce/plugin-sourcemod/releases/tag/3.12.2) zostało to naprawione
