### ISSUE TITLE
Sczytywanie SID graczy

### ISSUE THREAD

**Issue by Vakos321575** [gammerce/sklep-sms#399]
Cześć.
Sklep ma problem z dużą ilością użytkowników którzy podają SteamID w profilu w sklepie w celu możliwości kupna usług na serwerze za pomocą portfela.
Sklep po prostu ignoruje nowych użytkowników i twierdzi, że dana osoba nie podała swojego SID w profilu (informacja ukazuje się na serwerze).
Problem głównie dotyczy CS:GO ale możliwe iż CS 1.6 również ma z tym problem.

**Comment by budziam** [comment]
Cześć,
problemem jest brak miejsca w pamięci do trzymania wszystkich steam id. Jeżeli jest za dużo kont w sklepie, to pojawia się ten problem. Spróbuję zaimplementować poprawkę, która nie wymaga trzymania sid w pamięci, żeby problem nie występował niezależnie od ilości kont. 

Poprawka ta na pewno będzie wymagała zmian po stronie strony www oraz pluginu sm, także zajmie pewnie trochę czasu. Najwcześniej będę mógł się zająć pracą nad nią dopiero 10 stycznia.

**Comment by budziam** [comment]
@Vakos321575 wgranie najnowszej wersji pluginu [3.13.0](https://github.com/gammerce/plugin-sourcemod/releases/tag/3.13.0) powinno rozwiązac ten problem.
