### ISSUE TITLE
Zmiana hasła ACP

### ISSUE THREAD

**Issue by Weakus** [gammerce/sklep-sms#47]
A może tak dodać funkcję zmiany hasła przez panel admina? Przywracanie hasła poprzez e-mail jest słaby(strasznie wolny).

**Comment by budziam** [comment]
Myślę, że to bardzo dobry pomysł. Postaram się to dodać w kolejnej aktualizacji.

**Comment by budziam** [comment]
Funkcjonalność została zaimplementowana. Będzie dostępna wraz z nową wersją sklepu, która powinna pojawić się w następnym miesiącu.

**Comment by budziam** [comment]
@Weakus funkcjonalność została dodana w najnowszej wersji sklepu: https://github.com/gammerce/sklep-sms/releases/tag/3.8.0
