### ISSUE TITLE
Potrzebna pomoc

### ISSUE THREAD

**Issue by burrows787** [gammerce/sklep-sms#48]
Potrzebuje pomocy w konfiguracji sklepu, zrobilem krok po kroku i nic nie dziala

**Comment by budziam** [comment]
Opisz problem tak żebym mógł Ci pomóc :)

**Comment by burrows787** [comment]
Wrzuciłem sklep SMS na serwer oraz stronę, na stronie działała serwerze nie 

Wysłane z iPhone'a
