### ISSUE TITLE
Dodatkowa flaga ADMFLAG_RESERVATION przy zakupie flag ADMFLAG_CUSTOM

### ISSUE THREAD

**Issue by suppatimmo** [gammerce/sklep-sms#49]
Cześć,
Problem polega na tym, że ustawiona w panelu flaga np O przy zakupie zostaje dostarczana wraz z flagą "a", co jest błędem. W webowym panelu bankowo ustawione jest "o", plugin na serwer wg wzoru.

**Comment by budziam** [comment]
Cześć, błąd ten został naprawiony wraz z ostatnią aktualizacją pluginu do sourcemod https://github.com/gammerce/plugin-sourcemod/releases/tag/3.5.0
