### ISSUE TITLE
Sklep SMS - rekordy

### ISSUE THREAD

**Issue by Vakos321575** [gammerce/sklep-sms#62]
Po przenosinach bazy nie usuwa rekordow z ss_user_service_extra_flags a próba nadania alterow wywala błędy.
Czy jesteś w stanie wyjaśnić jak to naprawić?

**Comment by budziam** [comment]
Rekordy z `ss_user_service_extra_flags` powinny być usuwane przez CRONa, może jest błędnie skonfigurowany?
Co do błedów przy alterach, mógłbyś podać konkretne błędy, które Ci się pojawiają?
