### ISSUE TITLE
3.9.0

### ISSUE THREAD

**Issue by Weakus** [gammerce/sklep-sms#69]
Gdzieś błąd jest w sklepie, po wgraniu bulida przenosi do /setup i prosi o utworzenie pliku confidential/.env ;X

**Comment by budziam** [comment]
Z jakiej wersji aktualizowałeś sklep?

**Comment by Weakus** [comment]
3.8.0, sam zdziwiłem się, że owa informacja wyskakuje, oczywiście płuczek tam jest, chmody również ustawione.

**Comment by budziam** [comment]
A nie masz przypadkiem pliku pod ścieżką `includes/config.php`?

**Comment by Weakus** [comment]
Sens w tym, że nie mam. Wgrywałem czystą paczkę z wersji 3.8.0 i działa, po wgraniu 3.9.0, ukazuje się ta informacja.

**Comment by budziam** [comment]
Ah... błąd po mojej stronie. Plik `includes/Http/Controllers/View/SetupController.php` linijka 33.
Zamiast
```php
        if (!$oldShop->hasConfigFile()) {
```
Powinno być
```php
        if ($oldShop->hasConfigFile()) {
```

Możesz to poprawić u siebie ręcznie, a ja za chwilę podmienię zaktualizuję wersję 3.9.0

**Comment by Weakus** [comment]
Śmiga, dzięki wielkie ;p
