### ISSUE TITLE
Błąd wyszukiwania 

### ISSUE THREAD

**Issue by Vakos321575** [gammerce/sklep-sms#7]
Witam.
Sklep posiada błąd w wyszukiwaniu danej usługi po nicku bądź SID w zakładce "Czasowe usługi użytkowników".
Po wpisaniu znaków takich jak np ; : bądź użycia spacji  automatycznie po "Wyszukuj" zamienia na np: xd%s%s%
Czy problem mógłby zostać naprawiony?

**Comment by budziam** [comment]
Cześć,
problem został rozwiązany w commicie: https://github.com/gammerce/sklep-sms/commit/b41c921d8eb83abcb178a3e3dd754fa9d2676e75 i zostanie zawarty w nowej wersji sklepu 3.5.2
