### ISSUE TITLE
Logi zarobków 

### ISSUE THREAD

**Issue by DaveZ07** [gammerce/sklep-sms#77]
Po aktualizacji z wersji 3.8.0 na 3.9.2 nie dzialaja logi zarobków serwerów.

**Comment by naXe90** [comment]
Zapytanie, które zwraca przychód jest błędne i nie zwraca żadnych wyników.

**Comment by DaveZ07** [comment]
Kolejny błąd, przy próbie zmiany cennika uslug

Fatal error: Call to a member function getName() on null in /includes/Pages/PageAdminPriceList.php on line 55

**Comment by budziam** [comment]
Dzięki za zgłoszenia. Postaram się do końca dnia wypuścić wersję z poprawkami powyższych błędów. Proszę daj znać o wszystkich błędach na które się natkniesz.

**Comment by naXe90** [comment]
Naprawiłeś zakładkę Przychód, ale suma zarobiona na serwerach nie jest wyświetlana pod nazwą serwerów tylko Inne

**Comment by budziam** [comment]
Wypuściłem wersję 3.9.4 w której naprawionych zostaje kilka różnych błędów. Sprawdź proszę, czy rozwiązuje ona Twoje problemy.

**Comment by naXe90** [comment]
Błąd, który opisałem powyżej dalej wystepuje.

**Comment by DaveZ07** [comment]
Aktualnie na 3.9.4 suma zarobków serwerów pokazuje się na miejscu pierwszego serwera, zarobki pierwszego serwera na miejscu następnego, itd..., a zarobki ostatniego serwera tam gdzie powinna być suma zarobków wszystkich serwerów.

**Comment by budziam** [comment]
@naXe90 gdy użytkownik doładowuje portfel, to pieniądze te trafiają do kategorii inne. Nawet jeżeli później przy ich użyciu kupi coś na serwerze. Jest to niedogodność, którą planuję w przyszłości naprawić. Może to właśnie dzieje się u Ciebie?

@DaveZ07 dzięki za informację, przyjrzę się temu.

**Comment by budziam** [comment]
W pliku `includes/Pages/PageAdminIncome.php` trzeba zmienić

Linijkę 47 na poniższą
```php
$serversIds = [];
```

Oraz dodać nowa linijkę poniżej linii 51
```php
$serversIds[] = 0;
```

Tak żeby całość wyglądała następująco:
```php
        $serversIds = [];
        foreach ($this->heart->getServers() as $server) {
            $serversIds[] = $server->getId();
            $tableRow .= new HeadCell($server->getName());
        }
        $serversIds[] = 0;
```

Postaram się na dniach wypuścić kolejną wersję, która będzie zawierać tę zmianę.

**Comment by AdrianJagodznski** [comment]
@budziam 

`W sklepie dodanych jest 0 serwerów.`

To wyświetla się na głównej, a w sklepie mamy 7 serwerów, prawidłowo połączone, zaktualizowane.

**Comment by budziam** [comment]
@AdrianJagodznski błąd zostanie naprawiony w wersji 3.9.5 Dzięki za zgłoszenie

**Comment by AdrianJagodznski** [comment]
@budziam 
Ręcznie można to sobie jakoś poprawić, czy zaczekać?
Przy okazji zgłosiłem Ci dosyć uciążliwy problem (albo moją głupotę), którą warto by było szybko poprawić.
https://github.com/gammerce/sklep-sms/issues/84

**Comment by budziam** [comment]
Poprawka nie jest prosta niestety. Postaram się dzisiaj wypuścić nową wersję.
Co do innego zgłoszenia, to zapoznam się z nim w wolnej chwili.

**Comment by budziam** [comment]
Pojawiła się wersja 3.9.5, która powinna naprawiać wszystkie w/w błędy.
