### ISSUE TITLE
Nie działa domena sklep-sms.pl

### ISSUE THREAD

**Issue by budziam** [gammerce/sklep-sms#81]
Tak jak w temacie. Jestem w trakcie rozwiązywania tego problemu.

**Comment by DaveZ07** [comment]
Kiedy sklep zacznie działać?

**Comment by AdrianJagodznski** [comment]
How long men?

**Comment by budziam** [comment]
Wszystko zależy od hekko.pl gdzie jest wykupiona domena. Czekam aż ją aktywują.

**Comment by Kowalsky001** [comment]
@budziam postrasz ich NASKiem - to zawsze działa ;) 
Może jakiś alternatywny adres do sprawdzania licencji? Po IP czy coś... ?

**Comment by DaveZ07** [comment]
dokładnie, jakiś alternatywny adres najlepiej na ten czas. Z każdą godziną coraz większe straty.

**Comment by AdrianJagodznski** [comment]
@budziam jak masz zamiar to zrekompensować, ludzie nie mogą kupować usług.

**Comment by budziam** [comment]
Adres jest zapisany na sztywno w kodach pluginu. Musiałbym wypuścić nową wersję z sklepu i pluginów.
@AdrianJagodznski jestem tego świadom. Każdy kto doświadczył problemu będzie mógł liczyć na rekompensatę finansową.

**Comment by DaveZ07** [comment]
@budziam polecam wydać tę aktualizację, jeżeli sklep nie będzie działać dłużej niż dobę.

**Comment by Kowalsky001** [comment]
@budziam popieram prośbę @DaveZ07 ... zaraz mnie gracze zlinczują.

**Comment by p4strike** [comment]
Mam nadzieje, że na przyszłość nie będzie takich problemów, które będą powodować jakieś straty...

**Comment by AdrianJagodznski** [comment]
@p4strike co roku to samo, już drugi raz nie opłacił domeny

**Comment by budziam** [comment]
Za Waszą radą wypuściłem tymczasową, nową wersję sklepu z zmienionym adresem serwera licencyjnego.

https://github.com/gammerce/sklep-sms/releases/tag/3.9.3
https://github.com/gammerce/plugin-amxmodx/releases/tag/3.7.1
https://github.com/gammerce/plugin-sourcemod/releases/tag/3.6.1

**Comment by AdrianJagodznski** [comment]
@budziam Mogę prosić o lickę na 12h? Muszę przenieść sklep, a nie można wykupić bezpośrednio do Ciebie. Wole nie ryzykować blokadą jedynej działającej licki, gdy domena leży.

**Comment by Kowalsky001** [comment]
o działa strona...

**Comment by budziam** [comment]
Domena już działa prawidłowo.

**Comment by Kowalsky001** [comment]
@budziam teraz trzeba robić downgrade pluginów i web czy można poczekać do kolejnej aktualizacji?

**Comment by budziam** [comment]
@Kowalsky001 możesz zrobić downgrade do 3.9.2, aczkolwiek zachęcam do aktualizacji do wersji 3.9.4, która rozwiązuje kilka zgłoszonych problemów.

**Comment by MalinaCSM** [comment]
Witam, ja kompletnie nie mogę zalogować się do panelu, mogę prosić o jakąś pomoc?

**Comment by AdrianJagodznski** [comment]
@MalinaCSM odezwij się do mnie na GG :)
Misiu - masz mnie dodanego :D

**Comment by budziam** [comment]
Problem został rozwiązany.
