### ISSUE TITLE
Nie można edytować usługi

### ISSUE THREAD

**Issue by naXe90** [gammerce/sklep-sms#84]
Podczas zapisywania usługi (po edycji) wyskakuje błąd "Nie wszystkie pola formularza zostały prawidłowo wypełnione", a pod polem ID komunikat "Usługa o takim ID już istnieje."

**Comment by budziam** [comment]
Jestem świadom tego błędu. Pracuję nad jego naprawą.

**Comment by naXe90** [comment]
Czy po zmiane flag usługi nie powinno też ustawiać nowej flagi/usuwać usuniętej flagi w ss_player_flags?

**Comment by budziam** [comment]
Pojawiła się wersja 3.9.5: https://github.com/gammerce/sklep-sms/releases/tag/3.9.5, która naprawia błąd edycji usługi.

> Czy po zmiane flag usługi nie powinno też zmieniać flag w ss_player_flags?

Ciężko ocenić, ma to swoje plusy i minusy. Sklep został zaimplementowany w taki sposób, że po zakupie usługi flagi nie ulegają zmianie gdy dana usługa zostanie wyedytowana. Czy to dobrze, czy źle - sam nie wiem, ale tak to działa.
