### ISSUE TITLE
Błąd dodawania nowej metody płatności

### ISSUE THREAD

**Issue by AdrianJagodznski** [gammerce/sklep-sms#86]
Witam,
klonuje płatność pukawki, aby rozliczać serwery na 2 różne api jednego serwisu.
https://github.com/gammerce/sklep-sms/wiki/Dodanie-nowego-serwisu-obs%C5%82uguj%C4%85cego-p%C5%82atno%C5%9Bci-SMS
Zgodnie z w/w instrukcją 
Wykonuje poprawnie krok 1 zmieniając odpowiednie kolumny tak jak to ustawie w pliku ApiExample.php
Wykonuje krok 2 j/w
Wykonuje krok 3 klonując oryginalny plik .php pukawki i zmieniam class oraz id na takie jak ustawiłem w bazie
Wrzucam plik ApiExample.php  zgodnie z krokiem 4
Uruchamiam nową metodę płatności i otrzymuje błąd, że ta metoda płatności nie została zaimplementowana.
O co może chodzić?

Dodam, że zmieniając zawartość pliku .php zabijaki i edytując w bazie treść sms oraz numery druga płatność pukawki działa prawidłowo. Tylko przy dodaniu nowej jest jakiś problem.

**Comment by budziam** [comment]
Myślę, że może brakować zarejestrowania nowej metody płatności w pliku `includes/Providers/HeartServiceProvider.php`

Pracuję właśnie nad zmianą w sklepie, która umożliwi korzystanie z kilku konfiguracji jednej platformy płatności. To co teraz próbujesz zrobić będzie można "wyklikać" z poziomu panelu. Myślę, że gdzieś w styczniu powinna pojawić się nowa wersja sklepu z tą funkcjonalnością.

**Comment by budziam** [comment]
Wraz nową wersją sklepu https://github.com/gammerce/sklep-sms/releases/tag/3.10.0 została dodana funkcjonalność, która umożliwia tworzenie wielu konfiguracji tego samego API. Zachęcam do aktualizacji.
