### ISSUE TITLE
Nowa metoda platnosci - PayPal

### ISSUE THREAD

**Issue by DaveZ07** [gammerce/sklep-sms#87]
Czy jest opcja, aby dodać dodatkową metodę płatności centralnie przez PayPal?
Z tego co wiem, paypal udostępnia dokumentację api do tego 
https://developer.paypal.com/docs/api/overview/

**Comment by budziam** [comment]
Cześć, 
jak najbardziej jest taka opcja. Na chwilę obecną można skorzystać z integracji którą dostarcza tpay. Z tego co mi wiadomo nie pobierają od tego prowizji.

Na liście oczekujących metod płatności są:
* SimPay Direct Billing
* PSC
* PSC od CSSetti 

Niestety muszę jakoś priorytetyzowac te rzeczy.

**Comment by DaveZ07** [comment]
Dodaj proszę do tej listy api paypala :)

A masz juz jakieś informacje kiedy konkretnie wprowadzisz te metody platnosci?

**Comment by budziam** [comment]
Na chwilę obecną ciężko powiedzieć

**Comment by p4strike** [comment]
Czy byłaby możliwość dodania płatności Hotpay.pl?  Oferują szeroki zakres płatności. Dodatkowo z Ich usługi może korzystać osoba prywatna jak i firma :)

**Comment by budziam** [comment]
@p4strike w tym momencie pracuję nad dodaniem obsługi Direct Billing od SimPay. W kolejce jeszcze są płatności PSC oraz PayPal. Bardzo chętnie dodałbym obsługę `Hotpay`, ale niestety to wszystko wymaga czasu.

**Comment by budziam** [comment]
@p4strike czy z obecnie dostępnych API płatności żadna Ci nie odpowiada?

**Comment by Vakos321575** [comment]
@budziam 
Na jakim etapie jesteś z obsługą `HotPay`?

**Comment by budziam** [comment]
@Vakos321575 nie zajmowałem się tym jeszcze. Jeżeli ktoś jest chętny taki moduł napisać, to gorąco zachęcam. Aktualna instrukcja jak to zrobić znajduje się tutaj: https://github.com/gammerce/sklep-sms/wiki/Dodanie-nowego-modu%C5%82u-obs%C5%82uguj%C4%85cego-p%C5%82atno%C5%9Bci-SMS/_edit

**Comment by Vakos321575** [comment]
@budziam 
A co z przelewami online? Podałeś tylko sms.

**Comment by budziam** [comment]
@DaveZ07 wsparcie dla PayPal zostało dodane do sklepu. Na razie jest w fazie testów, ale powinno się pojawić wraz z kolejną wersją sklepu.
@Vakos321575 zabieram się teraz do pracy nad dodaniem wsparcia dla HotPay. Może się uda do końca tego miesiąca wypuścić nową wersję sklepu z wsparciem dla HotPay (sms, transfer, direct billing)

**Comment by budziam** [comment]
Wsparcie dla PayPal zostało dodane w wersji [3.15.0](https://github.com/gammerce/sklep-sms/releases/tag/3.15.0)
Jeżeli ktoś oczekuje wsparcia dla HotPay, załóż proszę osobne zgłoszenie.
