### ISSUE TITLE
Zmiana czcionki w formularzu SMS

### ISSUE THREAD

**Issue by naXe90** [gammerce/sklep-sms#89]
Proponuę zmienić czcionke nawet na monospace dla treści SMSa, numeru oraz kosztu w formularzu zakupu, ponieważ (w moim przypadku) w treści SMSa nie widać kropek - zlewają się.

Zmieniłem u siebie, dodałem już istniejąca w shop.css klase 'is-family-monospace' i wyglada to już przyzwoicie, plik /themes/default/payment_method_sms.html

`<div>
            <strong>{$lang->translate('price')}</strong>: <span class="is-family-monospace">{{
            $purchaseData->getTariff()->getSmsCostGross() }}</span> {{ $settings['currency'] }}
        </div>
        <br />

        <div id="sms_details">
            <table>
                <tr>
                    <td
                        colspan="3"
                        style="font-weight: bold; padding-bottom: 5px; font-size: 18px;"
                    >
                        {$lang->translate('sms_send_sms')}
                    </td>
                </tr>
                <tr>
                    <td class="has-text-right">{$lang->translate('sms_text')}</td>
                    <td style="width: 20px;"></td>
                    <td class="has-text-left is-family-monospace">{{ $smsCode }}</td>
                </tr>
                <tr>
                    <td class="has-text-right">{$lang->translate('sms_number')}</td>
                    <td></td>
                    <td class="has-text-left is-family-monospace">{{ $purchaseData->getTariff()->getNumber() }}</td>
                </tr>`

**Comment by budziam** [comment]
Dzięki za zgłoszenie. Poprawka zostanie zawarta w kolejnej wersji sklepu. Commit: https://github.com/gammerce/sklep-sms/commit/eb0a0f5ac9304df8858f10720092ad62b820b914
