### ISSUE TITLE
Serwis płątności microsms

### ISSUE THREAD

**Issue by Sn1p3rs** [gammerce/sklep-sms#90]
Problem z płatnością przelewem wszystko z strony usługodawcy jest ok kasa wpływa mi na konto zarejestrowane na microsms ale już na sklepie nie dodaje do konta kasy ani usług brak jakichkolwiek logów

**Comment by budziam** [comment]
Cześć, postaram się przetestować to API płatności. Możliwe, że coś się zmieniło po stronie MicroSMS.

**Comment by budziam** [comment]
Przetestowałem płatności MicroSMS na stronie https://demo.sklep-sms.pl/ Doładowałem portfel kwotą 2zł i wszystko prawidłowo zadziałało. Możesz spróbować na własną rękę.

Może Twój serwer znajduje się za jakimś proxy w stylu cloudflare, które nie przekazuje informacji o prawdziwym adresie IP? Podczas odbierania informacji o przelewie od microsms, sklep weryfikuje czy informacje przyszły z odpowiedniego adresu IP. Dzieje się to w pliku `includes/Verification/PaymentModules/Microsms.php` linijka: 150

**Comment by budziam** [comment]
Możesz, przy pomocy trybu testowego microsms, sprawdzić czy serwer zwraca odpowiednią odpowiedź, czy występuje jakiś błąd.
