### ISSUE TITLE
Platformy płatności po aktualizacji

### ISSUE THREAD

**Issue by naXe90** [gammerce/sklep-sms#97]
Aktualizowaniu sklepu do wersji 3.10.0, przebiegła pomyślnie. W poprzedniej wersji miałem swoją metodę płatności SMS, niby zmigrowało w kolumnie xxx_payment_platforms ta metoda została dodana, ale gdy chcę ją edytować w ACP to sypie błędami:

Kodu nie ruszałem, jest kompatybilny z poprzednią wersją sklepu

> 08.01.2020 16:25: {
    "message": "Invalid payment module",
    "file": "\/sklep\/includes\/System\/Heart.php",
    "line": 234,
    "code": 0,
    "trace": [
        {
            "file": "\/sklep\/includes\/Http\/Services\/DataFieldService.php",
            "line": 32,
            "function": "getPaymentModuleDataFields",
            "class": "App\\System\\Heart",
            "type": "->",
            "args": [
                "getpay"
            ]
        },
        {
            "file": "\/sklep\/includes\/Pages\/PageAdminPaymentPlatforms.php",
            "line": 118,
            "function": "renderDataFields",
            "class": "App\\Http\\Services\\DataFieldService",
            "type": "->",
            "args": [
                "modul_platnosci",
                {
                    "api": "klucz_api",
                    "sms_text": "tresc_sms",
                    "api_secret": "sekretny_klucz_api"
                }
            ]
        },
        {
            "file": "\/sklep\/includes\/Pages\/PageAdminPaymentPlatforms.php",
            "line": 93,
            "function": "getActionBoxContent",
            "class": "App\\Pages\\PageAdminPaymentPlatforms",
            "type": "->",
            "args": [
                "edit",
                {
                    "id": "1"
                }
            ]
        },
        {
            "file": "\/sklep\/includes\/Http\/Controllers\/Api\/Admin\/PageActionBoxResource.php",
            "line": 33,
            "function": "getActionBox",
            "class": "App\\Pages\\PageAdminPaymentPlatforms",
            "type": "->",
            "args": [
                "edit",
                {
                    "id": "1"
                }
            ]
        },
        {
            "function": "get",
            "class": "App\\Http\\Controllers\\Api\\Admin\\PageActionBoxResource",
            "type": "->",
            "args": [
                "payment_platforms",
                "edit",
                {
                    "attributes": {},
                    "request": {},
                    "query": {},
                    "server": {},
                    "files": {},
                    "cookies": {},
                    "headers": {}
                },
                {},
                {
                    "pageTitle": "Platformy p\u0142atno\u015bci"
                }
            ]
        },
        {
            "file": "\/sklep\/vendor\/illuminate\/container\/BoundMethod.php",
            "line": 29,
            "function": "call_user_func_array",
            "args": [
                [
                    {},
                    "get"
                ],
                [
                    "payment_platforms",
                    "edit",
                    {
                        "attributes": {},
                        "request": {},
                        "query": {},
                        "server": {},
                        "files": {},
                        "cookies": {},
                        "headers": {}
                    },
                    {},
                    {
                        "pageTitle": "Platformy p\u0142atno\u015bci"
                    }
                ]
            ]
        },
        {
            "file": "\/sklep\/vendor\/illuminate\/container\/BoundMethod.php",
            "line": 87,
            "function": "Illuminate\\Container\\{closure}",
            "class": "Illuminate\\Container\\BoundMethod",
            "type": "::",
            "args": []
        },
        {
            "file": "\/sklep\/vendor\/illuminate\/container\/BoundMethod.php",
            "line": 31,
            "function": "callBoundMethod",
            "class": "Illuminate\\Container\\BoundMethod",
            "type": "::",
            "args": [
                {
                    "contextual": []
                },
                [
                    {},
                    "get"
                ],
                {}
            ]
        },
        {
            "file": "\/sklep\/vendor\/illuminate\/container\/BoundMethod.php",
            "line": 60,
            "function": "call",
            "class": "Illuminate\\Container\\BoundMethod",
            "type": "::",
            "args": [
                {
                    "contextual": []
                },
                [
                    {},
                    "get"
                ],
                {
                    "pageId": "payment_platforms",
                    "actionBoxId": "edit"
                }
            ]
        },
        {
            "file": "\/sklep\/vendor\/illuminate\/container\/BoundMethod.php",
            "line": 24,
            "function": "callClass",
            "class": "Illuminate\\Container\\BoundMethod",
            "type": "::",
            "args": [
                {
                    "contextual": []
                },
                "App\\Http\\Controllers\\Api\\Admin\\PageActionBoxResource@get",
                {
                    "pageId": "payment_platforms",
                    "actionBoxId": "edit"
                },
                null
            ]
        },
        {
            "file": "\/sklep\/vendor\/illuminate\/container\/Container.php",
            "line": 539,
            "function": "call",
            "class": "Illuminate\\Container\\BoundMethod",
            "type": "::",
            "args": [
                {
                    "contextual": []
                },
                "App\\Http\\Controllers\\Api\\Admin\\PageActionBoxResource@get",
                {
                    "pageId": "payment_platforms",
                    "actionBoxId": "edit"
                },
                null
            ]
        },
        {
            "file": "\/sklep\/includes\/Routes\/RoutesManager.php",
            "line": 579,
            "function": "call",
            "class": "Illuminate\\Container\\Container",
            "type": "->",
            "args": [
                "App\\Http\\Controllers\\Api\\Admin\\PageActionBoxResource@get",
                {
                    "pageId": "payment_platforms",
                    "actionBoxId": "edit"
                }
            ]
        },
        {
            "file": "\/sklep\/includes\/Routes\/RoutesManager.php",
            "line": 549,
            "function": "handleFoundRoute",
            "class": "App\\Routes\\RoutesManager",
            "type": "->",
            "args": [
                [
                    1,
                    {
                        "middlewares": [
                            "App\\Http\\Middlewares\\SetAdminSession",
                            "App\\Http\\Middlewares\\IsUpToDate",
                            "App\\Http\\Middlewares\\LoadSettings",
                            "App\\Http\\Middlewares\\SetLanguage",
                            "App\\Http\\Middlewares\\ManageAdminAuthentication",
                            "App\\Http\\Middlewares\\ValidateLicense",
                            "App\\Http\\Middlewares\\UpdateUserActivity",
                            "App\\Http\\Middlewares\\RequireAuthorization"
                        ],
                        "uses": "App\\Http\\Controllers\\Api\\Admin\\PageActionBoxResource@get"
                    },
                    {
                        "pageId": "payment_platforms",
                        "actionBoxId": "edit"
                    }
                ],
                {
                    "attributes": {},
                    "request": {},
                    "query": {},
                    "server": {},
                    "files": {},
                    "cookies": {},
                    "headers": {}
                }
            ]
        },
        {
            "file": "\/sklep\/includes\/Routes\/RoutesManager.php",
            "line": 538,
            "function": "handleDispatcherResponse",
            "class": "App\\Routes\\RoutesManager",
            "type": "->",
            "args": [
                [
                    1,
                    {
                        "middlewares": [
                            "App\\Http\\Middlewares\\SetAdminSession",
                            "App\\Http\\Middlewares\\IsUpToDate",
                            "App\\Http\\Middlewares\\LoadSettings",
                            "App\\Http\\Middlewares\\SetLanguage",
                            "App\\Http\\Middlewares\\ManageAdminAuthentication",
                            "App\\Http\\Middlewares\\ValidateLicense",
                            "App\\Http\\Middlewares\\UpdateUserActivity",
                            "App\\Http\\Middlewares\\RequireAuthorization"
                        ],
                        "uses": "App\\Http\\Controllers\\Api\\Admin\\PageActionBoxResource@get"
                    },
                    {
                        "pageId": "payment_platforms",
                        "actionBoxId": "edit"
                    }
                ],
                {
                    "attributes": {},
                    "request": {},
                    "query": {},
                    "server": {},
                    "files": {},
                    "cookies": {},
                    "headers": {}
                }
            ]
        },
        {
            "file": "\/sklep\/includes\/Kernels\/Kernel.php",
            "line": 33,
            "function": "dispatch",
            "class": "App\\Routes\\RoutesManager",
            "type": "->",
            "args": [
                {
                    "attributes": {},
                    "request": {},
                    "query": {},
                    "server": {},
                    "files": {},
                    "cookies": {},
                    "headers": {}
                }
            ]
        },
        {
            "file": "\/sklep\/index.php",
            "line": 19,
            "function": "handle",
            "class": "App\\Kernels\\Kernel",
            "type": "->",
            "args": [
                {
                    "attributes": {},
                    "request": {},
                    "query": {},
                    "server": {},
                    "files": {},
                    "cookies": {},
                    "headers": {}
                }
            ]
        }
    ]
}

**Comment by budziam** [comment]
Myślę, że może mieć to związek z tym, że Twój plik do obsługi API nie jest kompatybilny z nową wersją sklepu. Zapoznaj się z aktualizowanym poradnikiem: https://github.com/gammerce/sklep-sms/wiki/Dodanie-nowego-modu%C5%82u-obs%C5%82uguj%C4%85cego-p%C5%82atno%C5%9Bci-SMS

Upewnij się, że:
1. Rejestrujesz swój moduł płatności. 
2. ID modułu podane jest w nowy sposób
```php
const MODULE_ID = "example";
```
a nie stary
```php
protected $id = "example";
```
3. Nie korzystasz bezpośrednio z pola `data`, tylko poprzez metodę `getData()`
4. Nie korzystasz bezpośrednio z pola `tarrifs`

**Comment by naXe90** [comment]
Tak jak napiasłem, nie zmieniałem kodu i moduł był zarejestrowany w poprzedniej wersji (3.9.5) poprawnie i działał. Teraz zarejestrowałem ponownie moduł w pliku HeartServiceProvider.php i przystosowałem kod do aktualnej wersji i działa.

Chodzi mi o to, że moim zdaniem po migracji kod powinien działać ze wstecznymi standardami, tak jak napisałeś to w wiki ;)

**Comment by budziam** [comment]
Tak byłoby idealnie. Ale czasami jest to bardzo trudne.
